"use client";

import { useState, useRef, useCallback } from "react";
import QRCode from "qrcode";

interface ReportData {
  symbol: string;
  companyName: string;
  exchange: string;
  // Price
  price?: number;
  changePct?: number;
  // Fundamentals
  marketCap?: string;
  peTtm?: string;
  peForward?: string;
  pbRatio?: string;
  beta?: string;
  dividendYield?: string;
  week52High?: string;
  week52Low?: string;
  sector?: string;
  industry?: string;
  profitMargin?: string;
  roe?: string;
  // TA signal
  taSignal?: string;
  taConfidence?: number;
  taWhatChanged?: string;
  taRelevance?: string;
  // Scan info
  lastScanDate?: string;
  totalScans?: number;
}

interface Props {
  data: ReportData;
  labels: Record<string, string>;
}

export default function ReportExportButton({ data, labels }: Props) {
  const [exporting, setExporting] = useState(false);
  const l = (key: string) => labels[key] || key;

  const handleExport = useCallback(async () => {
    setExporting(true);
    try {
      // Dynamic imports to reduce bundle size
      const html2canvas = (await import("html2canvas-pro")).default;
      const { jsPDF } = await import("jspdf");

      // Generate QR code
      const qrUrl = `https://stock.datap.ai/ticker/${data.symbol}?exchange=${data.exchange}`;
      const qrDataUrl = await QRCode.toDataURL(qrUrl, {
        width: 120,
        margin: 1,
        color: { dark: "#252525", light: "#ffffff" },
      });

      // Create hidden report element
      const container = document.createElement("div");
      container.style.cssText = "position:fixed;left:-9999px;top:0;width:800px;background:#0d1117;color:#e6edf3;font-family:system-ui,-apple-system,sans-serif;padding:40px;";

      const cp = data.exchange === "ASX" ? "A$" : data.exchange === "HKEX" ? "HK$" : data.exchange === "HOSE" ? "₫" : "$";
      const isUp = (data.changePct ?? 0) >= 0;
      const changeColor = isUp ? "#3fb950" : "#f85149";

      container.innerHTML = `
        <div style="border-bottom:2px solid #30363d;padding-bottom:24px;margin-bottom:24px;">
          <div style="display:flex;justify-content:space-between;align-items:flex-start;">
            <div>
              <div style="font-size:32px;font-weight:800;color:#ffffff;">${data.symbol}</div>
              <div style="font-size:16px;color:#8b949e;margin-top:4px;">${data.companyName}</div>
              <div style="font-size:12px;color:#484f58;margin-top:8px;">${data.exchange} · ${new Date().toLocaleDateString()} · Generated by DataP.ai</div>
            </div>
            <div style="text-align:right;">
              ${data.price ? `<div style="font-size:28px;font-weight:700;color:#ffffff;">${cp}${Number(data.price).toFixed(2)}</div>` : ""}
              ${data.changePct != null ? `<div style="font-size:16px;font-weight:600;color:${changeColor};margin-top:4px;">${isUp ? "+" : ""}${Number(data.changePct).toFixed(2)}%</div>` : ""}
            </div>
          </div>
        </div>

        <div style="color:#f0883e;font-size:14px;font-weight:600;margin-bottom:12px;text-transform:uppercase;letter-spacing:1px;">⚠ Disclaimer</div>
        <div style="color:#8b949e;font-size:11px;line-height:1.5;margin-bottom:24px;padding:12px;background:#161b22;border-radius:8px;border:1px solid #30363d;">
          ${l("rpt_disclaimer")}
        </div>

        ${data.marketCap || data.peTtm || data.sector ? `
        <div style="color:#58a6ff;font-size:14px;font-weight:600;margin-bottom:12px;text-transform:uppercase;letter-spacing:1px;">📊 ${l("sf_section_title")}</div>
        <div style="display:grid;grid-template-columns:1fr 1fr 1fr;gap:8px;margin-bottom:24px;">
          ${[
            [l("sf_market_cap"), data.marketCap],
            [l("sf_pe_ttm"), data.peTtm],
            [l("sf_pe_forward"), data.peForward],
            [l("sf_pb_ratio"), data.pbRatio],
            [l("sf_beta"), data.beta],
            [l("sf_dividend_yield"), data.dividendYield],
            [l("sf_52w_high"), data.week52High],
            [l("sf_52w_low"), data.week52Low],
            [l("sf_profit_margin"), data.profitMargin],
            [l("sf_roe"), data.roe],
            [l("sf_sector"), data.sector],
            [l("sf_industry"), data.industry],
          ].filter(([, v]) => v).map(([k, v]) =>
            `<div style="background:#161b22;border:1px solid #30363d;border-radius:6px;padding:8px 12px;">
              <div style="color:#8b949e;font-size:10px;">${k}</div>
              <div style="color:#e6edf3;font-size:13px;font-weight:600;margin-top:2px;">${v}</div>
            </div>`
          ).join("")}
        </div>
        ` : ""}

        ${data.taSignal ? `
        <div style="color:#58a6ff;font-size:14px;font-weight:600;margin-bottom:12px;text-transform:uppercase;letter-spacing:1px;">🤖 ${l("rpt_ai_signal")}</div>
        <div style="background:#161b22;border:1px solid #30363d;border-radius:8px;padding:16px;margin-bottom:24px;">
          <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:12px;">
            <span style="font-size:16px;font-weight:700;color:${data.taSignal?.includes("BUY") ? "#3fb950" : data.taSignal?.includes("SELL") ? "#f85149" : "#d29922"};">${data.taSignal}</span>
            ${data.taConfidence != null ? `<span style="color:#8b949e;font-size:13px;">Confidence: ${Math.round(data.taConfidence * 100)}%</span>` : ""}
          </div>
          ${data.taWhatChanged ? `<div style="color:#e6edf3;font-size:12px;line-height:1.6;margin-bottom:8px;"><strong style="color:#8b949e;">${l("rpt_what_changed")}:</strong> ${data.taWhatChanged}</div>` : ""}
          ${data.taRelevance ? `<div style="color:#e6edf3;font-size:12px;line-height:1.6;"><strong style="color:#8b949e;">${l("rpt_relevance")}:</strong> ${data.taRelevance}</div>` : ""}
        </div>
        ` : ""}

        ${data.lastScanDate ? `
        <div style="color:#8b949e;font-size:11px;margin-bottom:24px;">
          Last scanned: ${data.lastScanDate} · Total scans: ${data.totalScans ?? 0}
        </div>
        ` : ""}

        <div style="border-top:2px solid #30363d;padding-top:20px;display:flex;justify-content:space-between;align-items:center;">
          <div>
            <div style="font-size:18px;font-weight:700;color:#ffffff;">DataP.ai</div>
            <div style="color:#8b949e;font-size:11px;margin-top:4px;">AI-Powered Stock Research · 7 Markets · 8 Languages</div>
            <div style="color:#58a6ff;font-size:11px;margin-top:2px;">stock.datap.ai</div>
          </div>
          <div style="text-align:center;">
            <img src="${qrDataUrl}" width="100" height="100" style="border-radius:4px;" />
            <div style="color:#8b949e;font-size:9px;margin-top:4px;">${l("rpt_scan_to_view")}</div>
          </div>
        </div>
      `;

      document.body.appendChild(container);

      // Render to canvas
      const canvas = await html2canvas(container, {
        backgroundColor: "#0d1117",
        scale: 2,
        useCORS: true,
      });

      document.body.removeChild(container);

      // Generate PDF
      const imgData = canvas.toDataURL("image/png");
      const imgWidth = 210; // A4 width in mm
      const imgHeight = (canvas.height * imgWidth) / canvas.width;

      const pdf = new jsPDF("p", "mm", "a4");
      pdf.addImage(imgData, "PNG", 0, 0, imgWidth, imgHeight);
      pdf.save(`${data.symbol}_${data.exchange}_DataPai_Report.pdf`);

    } catch (err) {
      console.error("Export failed:", err);
    } finally {
      setExporting(false);
    }
  }, [data, l]);

  return (
    <button
      onClick={handleExport}
      disabled={exporting}
      className="inline-flex items-center gap-2 px-4 py-2 text-sm font-semibold rounded-lg bg-white/10 text-white hover:bg-white/20 border border-white/20 transition-all disabled:opacity-50"
    >
      {exporting ? (
        <>⏳ {l("btn_exporting") || "Generating..."}</>
      ) : (
        <>⬇️ {l("btn_download_report") || "Download Report"}</>
      )}
    </button>
  );
}
