"use client";

/**
 * TechAnalyticsPanel.tsx
 *
 * Unified client component providing two product-ready AI features on the
 * ticker detail page:
 *
 *  📈 Technical Signal  — multi-timeframe RSI/MACD/Bollinger/EMA analysis
 *                         generated by Gemini + GPT compliance reviewer
 *
 *  📊 Chart Vision      — renders a 3-panel dark chart (Price/RSI/MACD) and
 *                         sends it to Gemini Vision for pattern recognition
 *
 *  🎯 ASX Trading Signal (ASX tickers only)
 *                       — combines IR page text + live TA indicators for a
 *                         STRONG BUY/BUY/HOLD/SELL/STRONG SELL signal
 *
 * All calls are on-demand (button click) — no data is pre-fetched.
 */

import { useState } from "react";
import SimpleMarkdown from "./SimpleMarkdown";
import { t as tFn, type Lang } from "@/lib/translations";

// ─── Types ────────────────────────────────────────────────────────────────────

interface TaResult {
  signal_markdown: string;
  current_price:   number | null;
  change_pct:      number | null;
  rsi:             number | null;
  rsi_label:       string | null;
  trend:           string | null;
  macd_label:      string | null;
  bb_label:        string | null;
}

interface ChartResult {
  chart_b64:  string;
  analysis:   string;
  indicators: Record<string, number | string | null>;
}

interface Props {
  symbol:   string;
  exchange: string;         // "ASX" | "US" | "NASDAQ" | "NYSE"
  /** Latest IR page snapshot text (used as announcement body for ASX signal) */
  snapshotText?: string;
  /** Latest scan headline/summary (used as headline for ASX signal) */
  latestHeadline?: string;
  /** UI language passed from parent server component */
  lang?: Lang;
}

// ─── Signal badge colours ─────────────────────────────────────────────────────

function signalBadge(markdown: string) {
  const m = markdown.match(/\*\*Signal\*\*\s*[:\-]?\s*\[?([^\]\n*]+)\]?/i)
         ?? markdown.match(/\*\*Signal\*\*:\s*([A-Z/ ]+)/i);
  const raw = m ? m[1].trim() : "";

  const map: Record<string, { bg: string; color: string; label: string }> = {
    "STRONG BUY":   { bg: "#d1fae5", color: "#065f46", label: "STRONG BUY ↑↑" },
    "BUY":          { bg: "#ecfdf5", color: "#047857", label: "BUY ↑" },
    "HOLD/NEUTRAL": { bg: "#fffbea", color: "#92400e", label: "HOLD / NEUTRAL →" },
    "HOLD":         { bg: "#fffbea", color: "#92400e", label: "HOLD →" },
    "NEUTRAL":      { bg: "#fffbea", color: "#92400e", label: "NEUTRAL →" },
    "SELL":         { bg: "#fff1f2", color: "#be123c", label: "SELL ↓" },
    "STRONG SELL":  { bg: "#fee2e2", color: "#991b1b", label: "STRONG SELL ↓↓" },
    "NOT RELATED":  { bg: "#f3f4f6", color: "#6b7280", label: "NOT RELATED" },
  };

  for (const [key, cfg] of Object.entries(map)) {
    if (raw.toUpperCase().includes(key)) {
      return (
        <span
          className="inline-block px-4 py-1.5 rounded-full text-sm font-bold uppercase tracking-wide"
          style={{ background: cfg.bg, color: cfg.color, border: `1.5px solid ${cfg.color}40` }}
        >
          {cfg.label}
        </span>
      );
    }
  }
  return raw ? (
    <span className="inline-block px-4 py-1.5 rounded-full text-sm font-bold bg-gray-100 text-gray-700">
      {raw}
    </span>
  ) : null;
}

// ─── Quick indicator pill ─────────────────────────────────────────────────────

function Pill({ label, value }: { label: string; value: string | null }) {
  if (!value) return null;
  return (
    <span className="inline-flex items-center gap-1 text-xs px-2.5 py-1 rounded-full bg-white/80 border border-gray-200 text-gray-600 font-medium">
      <span className="text-gray-400">{label}</span>
      <span className="font-bold text-gray-800">{value}</span>
    </span>
  );
}

// ─── Chart modal ──────────────────────────────────────────────────────────────

function ChartModal({
  chart,
  onClose,
  lang = "en",
}: {
  chart: ChartResult;
  onClose: () => void;
  lang?: Lang;
}) {
  const T = (key: Parameters<typeof tFn>[1]) => tFn(lang, key);
  return (
    <div
      className="fixed inset-0 z-50 flex items-start justify-center overflow-y-auto p-4"
      style={{ background: "rgba(0,0,0,0.75)" }}
      onClick={(e) => { if (e.target === e.currentTarget) onClose(); }}
    >
      <div
        className="relative w-full max-w-4xl my-8 rounded-2xl overflow-hidden shadow-2xl"
        style={{ background: "#0e1117" }}
      >
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-white/10">
          <div>
            <span className="text-white font-bold text-lg">{T("panel_modal_title")}</span>
            <span className="ml-3 text-white/40 text-sm">Gemini Vision · {chart.indicators?.timeframe ?? "1d"}</span>
          </div>
          <button
            onClick={onClose}
            className="text-white/50 hover:text-white text-2xl leading-none transition-colors"
          >
            ×
          </button>
        </div>

        {/* Chart image */}
        <div className="px-6 pt-5">
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src={`data:image/png;base64,${chart.chart_b64}`}
            alt="Technical analysis chart"
            className="w-full rounded-xl"
            style={{ border: "1px solid rgba(255,255,255,0.1)" }}
          />
        </div>

        {/* Gemini analysis */}
        <div className="px-6 py-5">
          <div
            className="rounded-xl p-5 text-sm"
            style={{
              background: "rgba(255,255,255,0.05)",
              border: "1px solid rgba(255,255,255,0.12)",
              color: "#e2e8f0",
            }}
          >
            <SimpleMarkdown className="text-sm leading-relaxed">
              {chart.analysis}
            </SimpleMarkdown>
          </div>
        </div>

        {/* Close footer */}
        <div className="px-6 pb-5 flex justify-end">
          <button
            onClick={onClose}
            className="px-5 py-2 rounded-lg text-sm font-semibold border border-white/20 text-white/70 hover:text-white transition-colors"
          >
            {T("panel_modal_close")}
          </button>
        </div>
      </div>
    </div>
  );
}

// ─── Main component ───────────────────────────────────────────────────────────

export default function TechAnalyticsPanel({
  symbol,
  exchange,
  snapshotText,
  latestHeadline,
  lang = "en",
}: Props) {
  const isASX = exchange === "ASX";
  const cp = isASX ? "A$" : "$";
  const T = (key: Parameters<typeof tFn>[1]) => tFn(lang, key);

  // ── TA Signal state ──────────────────────────────────────────────────────
  const [taPhase, setTaPhase] = useState<"idle" | "loading" | "done" | "error">("idle");
  const [taResult, setTaResult] = useState<TaResult | null>(null);
  const [taError, setTaError]   = useState<string>("");
  const [taExpanded, setTaExpanded] = useState(true);

  const [taFromCache, setTaFromCache] = useState(false);

  async function runTaSignal(force = false) {
    setTaPhase("loading");
    setTaResult(null);
    setTaError("");
    setTaFromCache(false);
    try {
      const url = force
        ? `/api/ticker/${symbol}/ta-signal?fresh=1`
        : `/api/ticker/${symbol}/ta-signal`;
      const res = await fetch(url, {
        method: "POST",
        signal: AbortSignal.timeout(120_000),
      });
      let json: { ok?: boolean; data?: TaResult & { cached?: boolean }; error?: { message?: string } | string };
      try {
        json = await res.json();
      } catch {
        throw new Error(`Server returned non-JSON (HTTP ${res.status}). The agent backend may be starting up — please retry in a moment.`);
      }
      if (!res.ok || !json?.ok) {
        const msg = typeof json?.error === "object" ? json.error?.message : String(json?.error ?? "");
        throw new Error(msg || `HTTP ${res.status}`);
      }
      setTaResult(json.data as TaResult);
      setTaFromCache(json.data?.cached === true);
      setTaPhase("done");
    } catch (err) {
      setTaError(String(err));
      setTaPhase("error");
    }
  }

  // ── Chart Vision state ───────────────────────────────────────────────────
  const [chartPhase, setChartPhase] = useState<"idle" | "loading" | "done" | "error">("idle");
  const [chartResult, setChartResult] = useState<ChartResult | null>(null);
  const [chartError, setChartError]   = useState<string>("");
  const [showModal, setShowModal]     = useState(false);
  const [chartFromCache, setChartFromCache] = useState(false);

  async function runChartAnalysis(force = false) {
    setChartPhase("loading");
    setChartResult(null);
    setChartError("");
    setChartFromCache(false);
    try {
      const url = force
        ? `/api/ticker/${symbol}/chart-analysis?fresh=1`
        : `/api/ticker/${symbol}/chart-analysis`;
      const res = await fetch(url, {
        method: "POST",
        signal: AbortSignal.timeout(120_000),
      });
      let json: { ok?: boolean; data?: ChartResult & { cached?: boolean }; error?: { message?: string } | string };
      try {
        json = await res.json();
      } catch {
        throw new Error(`Server returned non-JSON (HTTP ${res.status}). Agent backend may be starting — please retry.`);
      }
      if (!res.ok || !json?.ok) {
        const msg = typeof json?.error === "object" ? json.error?.message : String(json?.error ?? "");
        throw new Error(msg || `HTTP ${res.status}`);
      }
      setChartResult(json.data as ChartResult);
      setChartFromCache(json.data?.cached === true);
      setChartPhase("done");
      setShowModal(true);
    } catch (err) {
      setChartError(String(err));
      setChartPhase("error");
    }
  }

  // ── ASX Trading Signal state ─────────────────────────────────────────────
  const [asxPhase, setAsxPhase] = useState<"idle" | "loading" | "done" | "error">("idle");
  const [asxResult, setAsxResult] = useState<TaResult | null>(null);
  const [asxError, setAsxError]   = useState<string>("");
  const [asxExpanded, setAsxExpanded] = useState(true);

  async function runAsxSignal() {
    setAsxPhase("loading");
    setAsxResult(null);
    setAsxError("");
    try {
      const res = await fetch(`/api/ticker/${symbol}/asx-trading-signal`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          announcement_text: snapshotText ?? "",
          headline: latestHeadline ?? `${symbol} Investor Relations Update`,
          doc_type: "IR Update",
          market_sensitive: false,
        }),
        signal: AbortSignal.timeout(180_000),
      });
      let json: { ok?: boolean; data?: TaResult; error?: { message?: string } | string };
      try {
        json = await res.json();
      } catch {
        throw new Error(`Server returned non-JSON. Agent backend may be starting — please retry.`);
      }
      if (!res.ok || !json?.ok) {
        const msg = typeof json?.error === "object" ? json.error?.message : String(json?.error ?? "");
        throw new Error(msg || `HTTP ${res.status}`);
      }
      setAsxResult(json.data as TaResult);
      setAsxPhase("done");
    } catch (err) {
      setAsxError(String(err));
      setAsxPhase("error");
    }
  }

  // ── Helper: loading spinner ──────────────────────────────────────────────
  const Spinner = ({ label }: { label: string }) => (
    <div className="flex items-center gap-3 py-2">
      <span className="animate-spin text-xl">⟳</span>
      <span className="text-white/80 text-sm font-medium animate-pulse">{label}</span>
    </div>
  );

  // ── Render ───────────────────────────────────────────────────────────────
  return (
    <div className="space-y-6">

      {/* ── Button row ──────────────────────────────────────────────────────── */}
      <div className="rounded-2xl p-6 bg-white border border-gray-200 shadow-sm">
        <div className="flex items-center justify-between flex-wrap gap-3 mb-4">
          <div>
            <h2 className="text-[#252525] font-bold text-xl">{T("panel_heading")}</h2>
            {/* Data provenance — makes TinyFish → AI pipeline explicit */}
            <div className="flex items-center gap-1.5 flex-wrap mt-1.5">
              <span className="text-xs font-semibold px-2 py-0.5 rounded"
                style={{ background: "#f0fdf4", color: "#166534", border: "1px solid #4ade8040" }}>
                {T("panel_tf")}
              </span>
              <span className="text-gray-400 text-xs">+</span>
              <span className="text-xs font-semibold px-2 py-0.5 rounded"
                style={{ background: "#f3f4f6", color: "#6b7280" }}>
                {T("panel_yf")}
              </span>
              <span className="text-gray-400 text-xs">→</span>
              <span className="text-xs font-semibold px-2 py-0.5 rounded"
                style={{ background: "#ede9fe", color: "#4f46e5" }}>
                {T("panel_ai")}
              </span>
              <span className="text-gray-400 text-xs">→</span>
              <span className="text-xs font-semibold px-2 py-0.5 rounded"
                style={{ background: "#fff7ed", color: "#c2410c" }}>
                {T("panel_sig")}
              </span>
            </div>
          </div>
          {/* Quick stats if TA already done */}
          {taResult && (
            <div className="flex items-center gap-2 flex-wrap">
              {taResult.current_price && (
                <Pill label="Price" value={`${cp}${taResult.current_price.toFixed(2)}`} />
              )}
              {taResult.rsi && (
                <Pill
                  label="RSI"
                  value={`${taResult.rsi.toFixed(1)} ${taResult.rsi_label === "OVERBOUGHT" ? "↑" : taResult.rsi_label === "OVERSOLD" ? "↓" : ""}`}
                />
              )}
              {taResult.trend && (
                <Pill label="Trend" value={taResult.trend.replace("TREND", "").replace("_", " ")} />
              )}
            </div>
          )}
        </div>

        <div className="flex items-center gap-3 flex-wrap">
          {/* Technical Signal button */}
          <button
            onClick={taPhase === "idle" || taPhase === "error" ? () => runTaSignal() : undefined}
            disabled={taPhase === "loading"}
            className="inline-flex items-center gap-2 px-5 py-2.5 rounded-lg font-bold text-sm transition-all hover:-translate-y-0.5 hover:shadow-lg disabled:opacity-60"
            style={{
              background: taPhase === "done" ? "#f0fdf4" : "#2e8b57",
              color: taPhase === "done" ? "#166534" : "#fff",
              border: taPhase === "done" ? "1.5px solid #4ade80" : "none",
            }}
          >
            {taPhase === "loading" ? (
              <><span className="animate-spin">⟳</span> {T("panel_btn_ta_loading")}</>
            ) : taPhase === "done" ? (
              T("panel_btn_ta_done")
            ) : (
              T("panel_btn_ta")
            )}
          </button>

          {/* Chart Vision button */}
          <button
            onClick={chartPhase === "idle" || chartPhase === "error" ? () => runChartAnalysis() : () => setShowModal(true)}
            disabled={chartPhase === "loading"}
            className="inline-flex items-center gap-2 px-5 py-2.5 rounded-lg font-bold text-sm transition-all hover:-translate-y-0.5 hover:shadow-lg disabled:opacity-60"
            style={{
              background: chartPhase === "done" ? "#ede9fe" : "#6366f1",
              color: chartPhase === "done" ? "#4f46e5" : "#fff",
              border: chartPhase === "done" ? "1.5px solid #a5b4fc" : "none",
            }}
          >
            {chartPhase === "loading" ? (
              <><span className="animate-spin">⟳</span> {T("panel_btn_chart_loading")}</>
            ) : chartPhase === "done" ? (
              T("panel_btn_chart_done")
            ) : (
              T("panel_btn_chart")
            )}
          </button>

          {/* ASX Trading Signal button (ASX only) */}
          {isASX && (
            <div className="flex flex-col gap-1">
              <button
                onClick={asxPhase === "idle" || asxPhase === "error" ? runAsxSignal : undefined}
                disabled={asxPhase === "loading"}
                className="inline-flex items-center gap-2 px-5 py-2.5 rounded-lg font-bold text-sm transition-all hover:-translate-y-0.5 hover:shadow-lg disabled:opacity-60"
                style={{
                  background: asxPhase === "done" ? "#fff7ed" : "#fd8412",
                  color: asxPhase === "done" ? "#c2410c" : "#fff",
                  border: asxPhase === "done" ? "1.5px solid #fb923c" : "none",
                }}
              >
                {asxPhase === "loading" ? (
                  <><span className="animate-spin">⟳</span> {T("panel_btn_asx_loading")}</>
                ) : asxPhase === "done" ? (
                  T("panel_btn_asx_done")
                ) : (
                  T("panel_btn_asx")
                )}
              </button>
              {/* Show IR snapshot context so TinyFish's role is visible */}
              {snapshotText && snapshotText.length > 50 && (
                <span className="text-xs text-gray-400 pl-1">
                  🌊 {lang === "zh" ? `使用 ${Math.min(snapshotText.length, 4000).toLocaleString()} 个${T("panel_tf_context")}` : `Using ${Math.min(snapshotText.length, 4000).toLocaleString()} ${T("panel_tf_context")}`}
                </span>
              )}
            </div>
          )}
        </div>

        {/* Loading messages */}
        {taPhase === "loading" && (
          <div className="mt-4">
            <Spinner label="Fetching live OHLCV data → computing indicators → generating Gemini signal → GPT review…" />
            <p className="text-gray-400 text-xs mt-1">{T("panel_ta_time")}</p>
          </div>
        )}
        {chartPhase === "loading" && (
          <div className="mt-4">
            <Spinner label="Fetching OHLCV → rendering 3-panel chart → Gemini Vision analysis…" />
            <p className="text-gray-400 text-xs mt-1">{T("panel_chart_time")}</p>
          </div>
        )}
        {asxPhase === "loading" && (
          <div className="mt-4">
            <Spinner label="Fetching ASX price data → combining with IR content → Gemini signal + GPT compliance review…" />
            <p className="text-gray-400 text-xs mt-1">{T("panel_asx_time")}</p>
          </div>
        )}

        {/* Error messages */}
        {taPhase === "error" && (
          <p className="mt-3 text-red-400 text-sm">⚠ TA Signal failed: {taError}</p>
        )}
        {chartPhase === "error" && (
          <p className="mt-3 text-red-400 text-sm">⚠ Chart Vision failed: {chartError}</p>
        )}
        {asxPhase === "error" && (
          <p className="mt-3 text-red-400 text-sm">⚠ ASX Signal failed: {asxError}</p>
        )}
      </div>

      {/* ── TA Signal result panel ───────────────────────────────────────────── */}
      {taPhase === "done" && taResult && (
        <div className="bg-white border border-gray-200 rounded-2xl shadow-sm overflow-hidden">
          <button
            className="w-full px-8 py-5 flex items-center justify-between border-b border-gray-100 text-left hover:bg-gray-50 transition-colors"
            onClick={() => setTaExpanded(!taExpanded)}
          >
            <div className="flex items-center gap-4 flex-wrap">
              <h2 className="text-2xl font-bold text-[#252525]">{T("panel_ta_title")}</h2>
              {signalBadge(taResult.signal_markdown)}
              {taResult.current_price && (
                <span className="text-gray-500 text-sm font-medium">
                  {cp}{taResult.current_price.toFixed(2)}
                  {taResult.change_pct != null && (
                    <span style={{ color: taResult.change_pct >= 0 ? "#2e8b57" : "#dc2626", marginLeft: 6 }}>
                      {taResult.change_pct >= 0 ? "+" : ""}{taResult.change_pct.toFixed(2)}%
                    </span>
                  )}
                </span>
              )}
            </div>
            <span className="text-gray-400 text-sm">{taExpanded ? T("panel_collapse") : T("panel_expand")}</span>
          </button>
          {taExpanded && (
            <div className="px-8 py-6">
              <div className="text-sm text-gray-700 leading-relaxed">
                <SimpleMarkdown>{taResult.signal_markdown}</SimpleMarkdown>
              </div>
              {/* Data provenance trail */}
              <div className="mt-5 pt-4 border-t border-gray-100 flex items-center gap-2 flex-wrap text-xs text-gray-300">
                <span className="font-semibold text-green-600">🌊 TinyFish</span>
                <span>→ Yahoo Finance OHLCV (5m/30m/1h/1d)</span>
                <span>→ RSI · MACD · Bollinger · EMA</span>
                <span>→ Gemini primary</span>
                <span>→ GPT‑4o compliance review</span>
                <span className="ml-auto italic">{T("panel_not_advice")}</span>
              </div>
            </div>
          )}
        </div>
      )}

      {/* ── ASX Trading Signal result panel ─────────────────────────────────── */}
      {asxPhase === "done" && asxResult && (
        <div className="bg-white border border-gray-200 rounded-2xl shadow-sm overflow-hidden">
          <button
            className="w-full px-8 py-5 flex items-center justify-between border-b border-gray-100 text-left hover:bg-gray-50 transition-colors"
            onClick={() => setAsxExpanded(!asxExpanded)}
          >
            <div className="flex items-center gap-4 flex-wrap">
              <h2 className="text-2xl font-bold text-[#252525]">{T("panel_asx_title")}</h2>
              {signalBadge(asxResult.signal_markdown)}
              {asxResult.current_price && (
                <span className="text-gray-500 text-sm font-medium">
                  A${asxResult.current_price.toFixed(2)}
                </span>
              )}
            </div>
            <span className="text-gray-400 text-sm">{asxExpanded ? T("panel_collapse") : T("panel_expand")}</span>
          </button>
          {asxExpanded && (
            <div className="px-8 py-6">
              <div className="mb-4 p-3 rounded-lg bg-amber-50 border border-amber-100 text-xs text-amber-700">
                {T("panel_asx_notice")}
              </div>
              <div className="text-sm text-gray-700 leading-relaxed">
                <SimpleMarkdown>{asxResult.signal_markdown}</SimpleMarkdown>
              </div>
              {/* Data provenance trail — TinyFish IR scan is the unique input */}
              <div className="mt-5 pt-4 border-t border-gray-100 flex items-center gap-2 flex-wrap text-xs text-gray-300">
                <span className="font-semibold text-green-600">🌊 TinyFish IR scan</span>
                <span>→ language change detection</span>
                <span>→ Yahoo Finance ASX price (multi-timeframe)</span>
                <span>→ Gemini (Google Search grounded)</span>
                <span>→ GPT‑4o review</span>
                <span className="ml-auto italic">{T("panel_not_advice")}</span>
              </div>
            </div>
          )}
        </div>
      )}

      {/* ── Chart Vision modal ───────────────────────────────────────────────── */}
      {showModal && chartResult && (
        <ChartModal chart={chartResult} onClose={() => setShowModal(false)} lang={lang} />
      )}
    </div>
  );
}
