"use client";

/**
 * TechAnalyticsPanel.tsx
 *
 * Unified client component providing two product-ready AI features on the
 * ticker detail page:
 *
 *  📈 Technical Signal  — multi-timeframe RSI/MACD/Bollinger/EMA analysis
 *                         generated by Gemini (Google Search grounded)
 *
 *  📊 Chart Vision      — renders a 3-panel dark chart (Price/RSI/MACD) and
 *                         sends it to Gemini Vision for pattern recognition
 *
 *  🎯 ASX Trading Signal (ASX tickers only)
 *                       — combines IR page text + live TA indicators for a
 *                         STRONG BUY/BUY/HOLD/SELL/STRONG SELL signal
 *
 * All calls are on-demand (button click) — no data is pre-fetched.
 */

import { useState, useEffect } from "react";
import SimpleMarkdown from "./SimpleMarkdown";
import { t as tFn, type Lang } from "@/lib/translations";

// ─── Types ────────────────────────────────────────────────────────────────────

interface TaResult {
  signal_markdown: string;
  current_price:   number | null;
  change_pct:      number | null;
  rsi:             number | null;
  rsi_label:       string | null;
  trend:           string | null;
  macd_label:      string | null;
  bb_label:        string | null;
}

interface ChartResult {
  chart_b64:  string;
  analysis:   string;
  indicators: Record<string, number | string | null>;
}

interface FaResult {
  signal_markdown:    string;
  fundamental_signal: string | null;
  fundamental_score:  number | null;
  company_name:       string | null;
  sector:             string | null;
  computed_at:        string | null;
  cached:             boolean;
}

interface MarketIntelResult {
  intel_markdown:    string;
  overall_stance:    string | null;   // BULLISH | NEUTRAL | BEARISH
  macro_themes:      string[];
  sector_themes:     string[];
  ticker_catalysts:  string[];
  black_swans:       string[];
  sources_used:      string[];        // e.g. ["Reuters Finance", "CFR Global Economy", ...]
  cached:            boolean;
  fetched_at:        string | null;
}

interface Props {
  symbol:   string;
  exchange: string;         // "ASX" | "US" | "NASDAQ" | "NYSE"
  /** Sector for Market Intel (e.g. "Technology") */
  sector?: string | null;
  /** Latest IR page snapshot text (used as announcement body for ASX signal) */
  snapshotText?: string;
  /** Latest scan headline/summary (used as headline for ASX signal) */
  latestHeadline?: string;
  /** UI language passed from parent server component */
  lang?: Lang;
  /** Slot: AI Research Co-pilot chat panel — rendered immediately after TA Signal result */
  chatSlot?: React.ReactNode;
  /** Auto-run a specific analysis on mount: "ta" | "fa" | "ma" | "ca" */
  autoRun?: string | null;
}

// ─── Signal badge colours ─────────────────────────────────────────────────────

function signalBadge(markdown: string) {
  const m = markdown.match(/\*\*Signal\*\*\s*[:\-]?\s*\[?([^\]\n*]+)\]?/i)
         ?? markdown.match(/\*\*Signal\*\*:\s*([A-Z/ ]+)/i);
  const raw = m ? m[1].trim() : "";

  const map: Record<string, { bg: string; color: string; label: string }> = {
    "STRONG BUY":   { bg: "#d1fae5", color: "#065f46", label: "STRONG BUY ↑↑" },
    "BUY":          { bg: "#ecfdf5", color: "#047857", label: "BUY ↑" },
    "HOLD/NEUTRAL": { bg: "#fffbea", color: "#92400e", label: "HOLD / NEUTRAL →" },
    "HOLD":         { bg: "#fffbea", color: "#92400e", label: "HOLD →" },
    "NEUTRAL":      { bg: "#fffbea", color: "#92400e", label: "NEUTRAL →" },
    "SELL":         { bg: "#fff1f2", color: "#be123c", label: "SELL ↓" },
    "STRONG SELL":  { bg: "#fee2e2", color: "#991b1b", label: "STRONG SELL ↓↓" },
    "NOT RELATED":  { bg: "#f3f4f6", color: "#6b7280", label: "NOT RELATED" },
  };

  for (const [key, cfg] of Object.entries(map)) {
    if (raw.toUpperCase().includes(key)) {
      return (
        <span
          className="inline-block px-4 py-1.5 rounded-full text-sm font-bold uppercase tracking-wide"
          style={{ background: cfg.bg, color: cfg.color, border: `1.5px solid ${cfg.color}40` }}
        >
          {cfg.label}
        </span>
      );
    }
  }
  return raw ? (
    <span className="inline-block px-4 py-1.5 rounded-full text-sm font-bold bg-gray-100 text-gray-700">
      {raw}
    </span>
  ) : null;
}

// ── FA fundamental signal badge ───────────────────────────────────────────────

function faSignalBadge(signal: string | null) {
  if (!signal) return null;
  const map: Record<string, { bg: string; color: string; label: string }> = {
    STRONG_BUY:  { bg: "#d1fae5", color: "#065f46", label: "STRONG BUY ↑↑" },
    BUY:         { bg: "#ecfdf5", color: "#047857", label: "BUY ↑" },
    NEUTRAL:     { bg: "#fffbea", color: "#92400e", label: "NEUTRAL →" },
    SELL:        { bg: "#fff1f2", color: "#be123c", label: "SELL ↓" },
    STRONG_SELL: { bg: "#fee2e2", color: "#991b1b", label: "STRONG SELL ↓↓" },
  };
  const cfg = map[signal] ?? { bg: "#f3f4f6", color: "#6b7280", label: signal.replace(/_/g, " ") };
  return (
    <span
      className="inline-block px-4 py-1.5 rounded-full text-sm font-bold uppercase tracking-wide"
      style={{ background: cfg.bg, color: cfg.color, border: `1.5px solid ${cfg.color}40` }}
    >
      {cfg.label}
    </span>
  );
}

// ── Market Intel stance badge ─────────────────────────────────────────────────

function stanceBadge(stance: string | null) {
  if (!stance) return null;
  const map: Record<string, { bg: string; color: string; border: string; label: string }> = {
    BULLISH:  { bg: "#d1fae5", color: "#065f46", border: "#4ade80",  label: "🐂 BULLISH" },
    NEUTRAL:  { bg: "#fffbea", color: "#92400e", border: "#fbbf24",  label: "⚖️ NEUTRAL" },
    BEARISH:  { bg: "#fee2e2", color: "#991b1b", border: "#fca5a5",  label: "🐻 BEARISH" },
  };
  const key = stance.toUpperCase();
  const cfg = map[key] ?? { bg: "#f3f4f6", color: "#6b7280", border: "#d1d5db", label: stance };
  return (
    <span
      className="inline-block px-4 py-1.5 rounded-full text-sm font-bold uppercase tracking-wide"
      style={{ background: cfg.bg, color: cfg.color, border: `1.5px solid ${cfg.border}` }}
    >
      {cfg.label}
    </span>
  );
}

// ─── Quick indicator pill ─────────────────────────────────────────────────────

function Pill({ label, value }: { label: string; value: string | null }) {
  if (!value) return null;
  return (
    <span className="inline-flex items-center gap-1 text-xs px-2.5 py-1 rounded-full bg-white/80 border border-gray-200 text-gray-600 font-medium">
      <span className="text-gray-400">{label}</span>
      <span className="font-bold text-gray-800">{value}</span>
    </span>
  );
}

// ─── Chart modal ──────────────────────────────────────────────────────────────

function ChartModal({
  chart,
  onClose,
  lang = "en",
}: {
  chart: ChartResult;
  onClose: () => void;
  lang?: Lang;
}) {
  const T = (key: Parameters<typeof tFn>[1]) => tFn(lang, key);
  return (
    <div
      className="fixed inset-0 z-50 flex items-start justify-center overflow-y-auto p-4"
      style={{ background: "rgba(0,0,0,0.5)" }}
      onClick={(e) => { if (e.target === e.currentTarget) onClose(); }}
    >
      <div
        className="relative w-full max-w-4xl my-8 rounded-2xl overflow-hidden shadow-2xl"
        style={{ background: "#ffffff" }}
      >
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-gray-200" style={{ background: "#f8fafc" }}>
          <div>
            <span className="text-gray-800 font-bold text-lg">{T("panel_modal_title")}</span>
            <span className="ml-3 text-gray-400 text-sm">Gemini Vision · {chart.indicators?.timeframe ?? "1d"}</span>
          </div>
          <button
            onClick={onClose}
            className="text-gray-400 hover:text-gray-700 text-2xl leading-none transition-colors"
          >
            ×
          </button>
        </div>

        {/* Chart image */}
        <div className="px-6 pt-5">
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src={`data:image/png;base64,${chart.chart_b64}`}
            alt="Technical analysis chart"
            className="w-full rounded-xl"
            style={{ border: "1px solid #e5e7eb" }}
          />
        </div>

        {/* Gemini analysis */}
        <div className="px-6 py-5">
          <div
            className="rounded-xl p-5 text-sm"
            style={{
              background: "#f8fafc",
              border: "1px solid #e2e8f0",
              color: "#374151",
            }}
          >
            <SimpleMarkdown className="text-sm leading-relaxed">
              {chart.analysis}
            </SimpleMarkdown>
          </div>
        </div>

        {/* Data provenance trail */}
        <div className="px-6 pb-3">
          <div className="flex items-center gap-2 flex-wrap text-xs text-gray-300">
            <span className="font-semibold text-indigo-500">🌊 TinyFish</span>
            <span>→ Yahoo Finance OHLCV</span>
            <span>→ 3-panel chart render</span>
            <span>→ Gemini Vision pattern recognition</span>
            <span className="ml-auto italic">{T("panel_not_advice")}</span>
          </div>
        </div>

        {/* Close footer */}
        <div className="px-6 pb-5 flex justify-end">
          <button
            onClick={onClose}
            className="px-5 py-2 rounded-lg text-sm font-semibold border border-gray-200 text-gray-500 hover:text-gray-700 hover:bg-gray-50 transition-colors"
          >
            {T("panel_modal_close")}
          </button>
        </div>
      </div>
    </div>
  );
}

// ─── Main component ───────────────────────────────────────────────────────────

export default function TechAnalyticsPanel({
  symbol,
  exchange,
  sector,
  snapshotText,
  latestHeadline,
  lang = "en",
  chatSlot,
  autoRun,
}: Props) {
  const isASX = exchange === "ASX";
  const cp = isASX ? "A$" : "$";
  const T = (key: Parameters<typeof tFn>[1]) => tFn(lang, key);

  // ── TA Signal state ──────────────────────────────────────────────────────
  const [taPhase, setTaPhase] = useState<"idle" | "loading" | "done" | "error">("idle");
  const [taResult, setTaResult] = useState<TaResult | null>(null);
  const [taError, setTaError]   = useState<string>("");
  const [taExpanded, setTaExpanded] = useState(true);

  const [taFromCache, setTaFromCache] = useState(false);

  async function runTaSignal(force = false) {
    setTaPhase("loading");
    setTaResult(null);
    setTaError("");
    setTaFromCache(false);
    try {
      const url = force
        ? `/api/ticker/${symbol}/ta-signal?fresh=1`
        : `/api/ticker/${symbol}/ta-signal`;
      const res = await fetch(url, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body:    JSON.stringify({ lang }),
        signal:  AbortSignal.timeout(120_000),
      });
      let json: { ok?: boolean; data?: TaResult & { cached?: boolean }; error?: { message?: string } | string };
      try {
        json = await res.json();
      } catch {
        throw new Error(`Server returned non-JSON (HTTP ${res.status}). The agent backend may be starting up — please retry in a moment.`);
      }
      if (!res.ok || !json?.ok) {
        const msg = typeof json?.error === "object" ? json.error?.message : String(json?.error ?? "");
        throw new Error(msg || `HTTP ${res.status}`);
      }
      setTaResult(json.data as TaResult);
      setTaFromCache(json.data?.cached === true);
      setTaPhase("done");
    } catch (err) {
      setTaError(String(err));
      setTaPhase("error");
    }
  }

  // ── Chart Vision state ───────────────────────────────────────────────────
  const [chartPhase, setChartPhase] = useState<"idle" | "loading" | "done" | "error">("idle");
  const [chartResult, setChartResult] = useState<ChartResult | null>(null);
  const [chartError, setChartError]   = useState<string>("");
  const [showModal, setShowModal]     = useState(false);
  const [chartFromCache, setChartFromCache] = useState(false);
  const [chartExpanded, setChartExpanded] = useState(true);

  async function runChartAnalysis(force = false) {
    setChartPhase("loading");
    setChartResult(null);
    setChartError("");
    setChartFromCache(false);
    try {
      const url = force
        ? `/api/ticker/${symbol}/chart-analysis?fresh=1`
        : `/api/ticker/${symbol}/chart-analysis`;
      const res = await fetch(url, {
        method:  "POST",
        headers: { "Content-Type": "application/json" },
        body:    JSON.stringify({ lang }),
        signal:  AbortSignal.timeout(120_000),
      });
      let json: { ok?: boolean; data?: ChartResult & { cached?: boolean }; error?: { message?: string } | string };
      try {
        json = await res.json();
      } catch {
        throw new Error(`Server returned non-JSON (HTTP ${res.status}). Agent backend may be starting — please retry.`);
      }
      if (!res.ok || !json?.ok) {
        const msg = typeof json?.error === "object" ? json.error?.message : String(json?.error ?? "");
        throw new Error(msg || `HTTP ${res.status}`);
      }
      setChartResult(json.data as ChartResult);
      setChartFromCache(json.data?.cached === true);
      setChartPhase("done");
      setShowModal(true);
    } catch (err) {
      setChartError(String(err));
      setChartPhase("error");
    }
  }

  // ── ASX Trading Signal state ─────────────────────────────────────────────
  const [asxPhase, setAsxPhase] = useState<"idle" | "loading" | "done" | "error">("idle");
  const [asxResult, setAsxResult] = useState<TaResult | null>(null);
  const [asxError, setAsxError]   = useState<string>("");
  const [asxExpanded, setAsxExpanded] = useState(true);

  // ── FA Fundamental Analysis state ────────────────────────────────────────
  const [faPhase, setFaPhase] = useState<"idle" | "loading" | "done" | "error">("idle");
  const [faResult, setFaResult] = useState<FaResult | null>(null);
  const [faError, setFaError]   = useState<string>("");
  const [faExpanded, setFaExpanded] = useState(true);

  // ── Market Intelligence state ─────────────────────────────────────────────
  const [miPhase, setMiPhase] = useState<"idle" | "loading" | "done" | "error">("idle");
  const [miResult, setMiResult] = useState<MarketIntelResult | null>(null);
  const [miError, setMiError]   = useState<string>("");
  const [miExpanded, setMiExpanded] = useState(true);

  // ── Auto-run when parent passes autoRun prop ─────────────────────────────
  useEffect(() => {
    if (!autoRun) return;
    if (autoRun === "ta") runTaSignal();
    else if (autoRun === "fa") runFaAnalysis();
    else if (autoRun === "ma") runMarketIntel();
    else if (autoRun === "ca") runChartAnalysis();
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  async function runMarketIntel(force = false) {
    setMiPhase("loading");
    setMiResult(null);
    setMiError("");
    try {
      const params = new URLSearchParams({ exchange });
      if (sector) params.set("sector", sector);
      if (force)  params.set("fresh", "1");
      const res = await fetch(
        `/api/ticker/${symbol}/market-intel?${params}`,
        { signal: AbortSignal.timeout(180_000) }   // TinyFish × 3 + LLM synthesis ≤ 3 min
      );
      let json: { ok?: boolean; data?: MarketIntelResult; error?: string | { message?: string } };
      try {
        json = await res.json();
      } catch {
        throw new Error(`Server returned non-JSON (HTTP ${res.status}). Agent backend may be starting — retry.`);
      }
      if (!res.ok || !json?.ok) {
        const msg =
          typeof json?.error === "object" ? json.error?.message : String(json?.error ?? `HTTP ${res.status}`);
        throw new Error(msg || `HTTP ${res.status}`);
      }
      setMiResult(json.data as MarketIntelResult);
      setMiPhase("done");
    } catch (err) {
      setMiError(String(err));
      setMiPhase("error");
    }
  }

  async function runFaAnalysis() {
    setFaPhase("loading");
    setFaResult(null);
    setFaError("");
    try {
      const res = await fetch(
        `/api/ticker/${symbol}/fa-signal?exchange=${encodeURIComponent(exchange)}`,
        { signal: AbortSignal.timeout(30_000) }
      );
      let json: { ok?: boolean; data?: FaResult; error?: string };
      try {
        json = await res.json();
      } catch {
        throw new Error(`Server returned non-JSON (HTTP ${res.status}). Agent backend may be starting — retry.`);
      }
      if (!res.ok || !json?.ok) {
        throw new Error(String(json?.error ?? `HTTP ${res.status}`));
      }
      setFaResult(json.data as FaResult);
      setFaPhase("done");
    } catch (err) {
      setFaError(String(err));
      setFaPhase("error");
    }
  }

  async function runAsxSignal() {
    setAsxPhase("loading");
    setAsxResult(null);
    setAsxError("");
    try {
      const res = await fetch(`/api/ticker/${symbol}/asx-trading-signal`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          announcement_text: snapshotText ?? "",
          headline: latestHeadline ?? `${symbol} Investor Relations Update`,
          doc_type: "IR Update",
          market_sensitive: false,
          lang,
        }),
        signal: AbortSignal.timeout(180_000),
      });
      let json: { ok?: boolean; data?: TaResult; error?: { message?: string } | string };
      try {
        json = await res.json();
      } catch {
        throw new Error(`Server returned non-JSON. Agent backend may be starting — please retry.`);
      }
      if (!res.ok || !json?.ok) {
        const msg = typeof json?.error === "object" ? json.error?.message : String(json?.error ?? "");
        throw new Error(msg || `HTTP ${res.status}`);
      }
      setAsxResult(json.data as TaResult);
      setAsxPhase("done");
    } catch (err) {
      setAsxError(String(err));
      setAsxPhase("error");
    }
  }

  // ── Helper: loading spinner ──────────────────────────────────────────────
  const Spinner = ({ label }: { label: string }) => (
    <div className="flex items-center gap-3 py-2">
      <span className="animate-spin text-xl text-[#2e8b57]">⟳</span>
      <span className="text-gray-500 text-sm font-medium animate-pulse">{label}</span>
    </div>
  );

  // ── Render ───────────────────────────────────────────────────────────────
  return (
    <div className="space-y-6">

      {/* ── Button row ──────────────────────────────────────────────────────── */}
      <div className="rounded-2xl p-6 bg-white border border-gray-200 shadow-sm">
        <div className="flex items-center justify-between flex-wrap gap-3 mb-4">
          <div>
            {/* Data provenance — makes TinyFish → AI pipeline explicit */}
            <div className="flex items-center gap-1.5 flex-wrap">
              <span className="text-xs font-semibold px-2 py-0.5 rounded"
                style={{ background: "#f0fdf4", color: "#166534", border: "1px solid #4ade8040" }}>
                {T("panel_tf")}
              </span>
              <span className="text-gray-400 text-xs">+</span>
              <span className="text-xs font-semibold px-2 py-0.5 rounded"
                style={{ background: "#f3f4f6", color: "#6b7280" }}>
                {T("panel_yf")}
              </span>
              <span className="text-gray-400 text-xs">→</span>
              <span className="text-xs font-semibold px-2 py-0.5 rounded"
                style={{ background: "#ede9fe", color: "#4f46e5" }}>
                {T("panel_ai")}
              </span>
              <span className="text-gray-400 text-xs">→</span>
              <span className="text-xs font-semibold px-2 py-0.5 rounded"
                style={{ background: "#fff7ed", color: "#c2410c" }}>
                {T("panel_sig")}
              </span>
            </div>
          </div>
          {/* Quick stats if TA already done */}
          {taResult && (
            <div className="flex items-center gap-2 flex-wrap">
              {taResult.current_price && (
                <Pill label="Price" value={`${cp}${taResult.current_price.toFixed(2)}`} />
              )}
              {taResult.rsi && (
                <Pill
                  label="RSI"
                  value={`${taResult.rsi.toFixed(1)} ${taResult.rsi_label === "OVERBOUGHT" ? "↑" : taResult.rsi_label === "OVERSOLD" ? "↓" : ""}`}
                />
              )}
              {taResult.trend && (
                <Pill label="Trend" value={taResult.trend.replace("TREND", "").replace("_", " ")} />
              )}
            </div>
          )}
        </div>

        <div className="flex items-center gap-3 flex-wrap">
          {/* Technical Signal button */}
          <button
            onClick={taPhase === "idle" || taPhase === "error" ? () => runTaSignal() : undefined}
            disabled={taPhase === "loading"}
            className="inline-flex items-center gap-2 px-5 py-2.5 rounded-lg font-bold text-sm transition-all hover:-translate-y-0.5 hover:shadow-lg disabled:opacity-60"
            style={{
              background: taPhase === "done" ? "#f0fdf4" : "#2e8b57",
              color: taPhase === "done" ? "#166534" : "#fff",
              border: taPhase === "done" ? "1.5px solid #4ade80" : "none",
            }}
          >
            {taPhase === "loading" ? (
              <><span className="animate-spin">⟳</span> {T("panel_btn_ta_loading")}</>
            ) : taPhase === "done" ? (
              T("panel_btn_ta_done")
            ) : (
              T("panel_btn_ta")
            )}
          </button>

          {/* Chart Vision button */}
          <button
            onClick={chartPhase === "idle" || chartPhase === "error" ? () => runChartAnalysis() : () => setShowModal(true)}
            disabled={chartPhase === "loading"}
            className="inline-flex items-center gap-2 px-5 py-2.5 rounded-lg font-bold text-sm transition-all hover:-translate-y-0.5 hover:shadow-lg disabled:opacity-60"
            style={{
              background: chartPhase === "done" ? "#ede9fe" : "#6366f1",
              color: chartPhase === "done" ? "#4f46e5" : "#fff",
              border: chartPhase === "done" ? "1.5px solid #a5b4fc" : "none",
            }}
          >
            {chartPhase === "loading" ? (
              <><span className="animate-spin">⟳</span> {T("panel_btn_chart_loading")}</>
            ) : chartPhase === "done" ? (
              T("panel_btn_chart_done")
            ) : (
              T("panel_btn_chart")
            )}
          </button>

          {/* Fundamental Analysis button */}
          <button
            onClick={faPhase === "idle" || faPhase === "error" ? runFaAnalysis : undefined}
            disabled={faPhase === "loading"}
            className="inline-flex items-center gap-2 px-5 py-2.5 rounded-lg font-bold text-sm transition-all hover:-translate-y-0.5 hover:shadow-lg disabled:opacity-60"
            style={{
              background: faPhase === "done" ? "#fff7ed" : "#f59e0b",
              color:      faPhase === "done" ? "#b45309" : "#fff",
              border:     faPhase === "done" ? "1.5px solid #fbbf24" : "none",
            }}
          >
            {faPhase === "loading" ? (
              <><span className="animate-spin">⟳</span> Loading FA…</>
            ) : faPhase === "done" ? (
              "📊 Fundamentals ✓"
            ) : (
              "📊 Fundamental Analysis"
            )}
          </button>

          {/* 🌐 Market Intelligence button — TinyFish live crawl + senior analyst synthesis */}
          <button
            onClick={miPhase === "idle" || miPhase === "error" ? () => runMarketIntel() : undefined}
            disabled={miPhase === "loading"}
            className="inline-flex items-center gap-2 px-5 py-2.5 rounded-lg font-bold text-sm transition-all hover:-translate-y-0.5 hover:shadow-lg disabled:opacity-60"
            style={{
              background: miPhase === "done" ? "#ecfeff" : "#0891b2",
              color:      miPhase === "done" ? "#0e7490" : "#fff",
              border:     miPhase === "done" ? "1.5px solid #67e8f9" : "none",
            }}
          >
            {miPhase === "loading" ? (
              <><span className="animate-spin">⟳</span> Crawling Markets…</>
            ) : miPhase === "done" ? (
              "🌐 MA ✓"
            ) : (
              "🌐 Market Analysis (MA)"
            )}
          </button>

          {/* ASX Trading Signal button (ASX only) */}
          {isASX && (
            <div className="flex flex-col gap-1">
              <button
                onClick={asxPhase === "idle" || asxPhase === "error" ? runAsxSignal : undefined}
                disabled={asxPhase === "loading"}
                className="inline-flex items-center gap-2 px-5 py-2.5 rounded-lg font-bold text-sm transition-all hover:-translate-y-0.5 hover:shadow-lg disabled:opacity-60"
                style={{
                  background: asxPhase === "done" ? "#fff7ed" : "#fd8412",
                  color: asxPhase === "done" ? "#c2410c" : "#fff",
                  border: asxPhase === "done" ? "1.5px solid #fb923c" : "none",
                }}
              >
                {asxPhase === "loading" ? (
                  <><span className="animate-spin">⟳</span> {T("panel_btn_asx_loading")}</>
                ) : asxPhase === "done" ? (
                  T("panel_btn_asx_done")
                ) : (
                  T("panel_btn_asx")
                )}
              </button>
              {/* Show IR snapshot context so TinyFish's role is visible */}
              {snapshotText && snapshotText.length > 50 && (
                <span className="text-xs text-gray-400 pl-1">
                  🌊 {lang === "zh" ? `使用 ${Math.min(snapshotText.length, 4000).toLocaleString()} 个${T("panel_tf_context")}` : `Using ${Math.min(snapshotText.length, 4000).toLocaleString()} ${T("panel_tf_context")}`}
                </span>
              )}
            </div>
          )}
        </div>

        {/* Loading messages */}
        {taPhase === "loading" && (
          <div className="mt-4">
            <Spinner label="Fetching live OHLCV data → computing indicators → generating Gemini signal…" />
            <p className="text-gray-400 text-xs mt-1">{T("panel_ta_time")}</p>
          </div>
        )}
        {chartPhase === "loading" && (
          <div className="mt-4">
            <Spinner label="Fetching OHLCV → rendering 3-panel chart → Gemini Vision analysis…" />
            <p className="text-gray-400 text-xs mt-1">{T("panel_chart_time")}</p>
          </div>
        )}
        {asxPhase === "loading" && (
          <div className="mt-4">
            <Spinner label="Fetching ASX price data → combining with IR content → Gemini signal…" />
            <p className="text-gray-400 text-xs mt-1">{T("panel_asx_time")}</p>
          </div>
        )}
        {faPhase === "loading" && (
          <div className="mt-4">
            <Spinner label="Reading fundamental snapshot → valuation · quality · growth · macro context…" />
            <p className="text-gray-400 text-xs mt-1">Typically &lt;5 s — reading nightly-computed cache</p>
          </div>
        )}
        {miPhase === "loading" && (
          <div className="mt-4">
            <Spinner label="TinyFish crawling Yahoo Finance markets + ticker news + sector pages…" />
            <p className="text-gray-400 text-xs mt-1">
              3 parallel TinyFish crawls → senior analyst LLM synthesis. Takes 60–120 s.
            </p>
          </div>
        )}

        {/* Error messages */}
        {taPhase === "error" && (
          <p className="mt-3 text-red-400 text-sm">⚠ TA Signal failed: {taError}</p>
        )}
        {chartPhase === "error" && (
          <p className="mt-3 text-red-400 text-sm">⚠ Chart Analysis (CA) failed: {chartError}</p>
        )}
        {asxPhase === "error" && (
          <p className="mt-3 text-red-400 text-sm">⚠ ASX Signal failed: {asxError}</p>
        )}
        {faPhase === "error" && (
          <div className="mt-3">
            <p className="text-amber-500 text-sm">⚠ Fundamental Analysis: {faError}</p>
            {faError.includes("No fundamental data") && (
              <p className="text-xs text-gray-400 mt-1">
                Fundamental data is computed nightly. This ticker may not have been processed yet.
                Run: <code className="bg-gray-100 px-1 rounded">python3 scripts/compute_fundamental_daily.py --exchange {exchange} --tickers {symbol}</code>
              </p>
            )}
          </div>
        )}
        {miPhase === "error" && (
          <div className="mt-3">
            <p className="text-red-400 text-sm">⚠ Market Analysis (MA) failed: {miError}</p>
            <p className="text-xs text-gray-400 mt-1">
              TinyFish may be rate-limiting or the Python backend is offline. Try again in a moment.
            </p>
          </div>
        )}
      </div>

      {/* ── TA Signal result panel ───────────────────────────────────────────── */}
      {taPhase === "done" && taResult && (
        <div className="bg-white border border-gray-200 rounded-2xl shadow-sm overflow-hidden">
          <button
            className="w-full px-8 py-5 flex items-center justify-between border-b border-gray-100 text-left hover:bg-gray-50 transition-colors"
            onClick={() => setTaExpanded(!taExpanded)}
          >
            <div className="flex items-center gap-4 flex-wrap">
              <h2 className="text-2xl font-bold text-[#252525]">{T("panel_ta_title")}</h2>
              {signalBadge(taResult.signal_markdown)}
              {taResult.current_price && (
                <span className="text-gray-500 text-sm font-medium">
                  {cp}{taResult.current_price.toFixed(2)}
                  {taResult.change_pct != null && (
                    <span style={{ color: taResult.change_pct >= 0 ? "#2e8b57" : "#dc2626", marginLeft: 6 }}>
                      {taResult.change_pct >= 0 ? "+" : ""}{taResult.change_pct.toFixed(2)}%
                    </span>
                  )}
                </span>
              )}
            </div>
            <span className="text-gray-400 text-sm">{taExpanded ? T("panel_collapse") : T("panel_expand")}</span>
          </button>
          {taExpanded && (
            <div className="px-8 py-6">
              <div className="text-sm text-gray-700 leading-relaxed">
                <SimpleMarkdown>{taResult.signal_markdown}</SimpleMarkdown>
              </div>
              {/* Data provenance trail */}
              <div className="mt-5 pt-4 border-t border-gray-100 flex items-center gap-2 flex-wrap text-xs text-gray-300">
                <span className="font-semibold text-green-600">🌊 TinyFish</span>
                <span>→ Yahoo Finance OHLCV (5m/30m/1h/1d)</span>
                <span>→ RSI · MACD · Bollinger · EMA</span>
                <span>→ Gemini (Google Search grounded)</span>
                <span className="ml-auto italic">{T("panel_not_advice")}</span>
              </div>
            </div>
          )}
        </div>
      )}

      {/* ── AI Research Co-pilot — rendered right after TA Signal ──────────── */}
      {chatSlot && (
        <div
          className="rounded-2xl overflow-hidden"
          style={{
            border: "2px solid #4ade80",
            background: "linear-gradient(to bottom, #f0fdf4, #ffffff)",
            boxShadow: "0 2px 16px 0 rgba(46,139,87,0.08)",
          }}
        >
          {/* Green header bar */}
          <div
            className="px-6 py-3 flex items-center gap-2"
            style={{ background: "#f0fdf4", borderBottom: "1.5px solid #bbf7d0" }}
          >
            <span className="text-lg">🤖</span>
            <span className="font-bold text-green-800 text-base">AI Research Co-pilot</span>
            <span className="text-xs text-green-600 font-medium ml-1">— ask anything about this stock</span>
          </div>
          <div className="p-0">
            {chatSlot}
          </div>
        </div>
      )}

      {/* ── Fundamental Analysis result panel ───────────────────────────────── */}
      {faPhase === "done" && faResult && (
        <div className="bg-white border border-gray-200 rounded-2xl shadow-sm overflow-hidden">
          <button
            className="w-full px-8 py-5 flex items-center justify-between border-b border-gray-100 text-left hover:bg-gray-50 transition-colors"
            onClick={() => setFaExpanded(!faExpanded)}
          >
            <div className="flex items-center gap-4 flex-wrap">
              <h2 className="text-2xl font-bold text-[#252525]">📊 Fundamental Analysis</h2>
              {faSignalBadge(faResult.fundamental_signal)}
              {faResult.fundamental_score !== null && (
                <span className="text-gray-500 text-sm font-medium tabular-nums">
                  Score: {faResult.fundamental_score.toFixed(3)}
                </span>
              )}
              {faResult.computed_at && (
                <span className="text-gray-400 text-xs">Updated {faResult.computed_at.slice(0, 10)}</span>
              )}
            </div>
            <span className="text-gray-400 text-sm">{faExpanded ? T("panel_collapse") : T("panel_expand")}</span>
          </button>
          {faExpanded && (
            <div className="px-8 py-6">
              <div className="text-sm text-gray-700 leading-relaxed">
                <SimpleMarkdown>{faResult.signal_markdown}</SimpleMarkdown>
              </div>
              {/* Data provenance trail */}
              <div className="mt-5 pt-4 border-t border-gray-100 flex items-center gap-2 flex-wrap text-xs text-gray-300">
                <span className="font-semibold text-amber-600">yfinance</span>
                <span>→ P/E · Margins · FCF · Growth rates · Balance sheet</span>
                <span>→ Gemini grounding (macro + geopolitical)</span>
                <span>→ AI narrative summary</span>
                <span className="ml-auto italic">{T("panel_not_advice")}</span>
              </div>
            </div>
          )}
        </div>
      )}

      {/* ── Market Intelligence result panel ────────────────────────────────── */}
      {miPhase === "done" && miResult && (
        <div
          className="bg-white rounded-2xl shadow-sm overflow-hidden"
          style={{ border: "2px solid #67e8f9" }}
        >
          {/* Collapsible header */}
          <button
            className="w-full px-8 py-5 flex items-center justify-between border-b text-left hover:bg-cyan-50/50 transition-colors"
            style={{ borderBottomColor: "#a5f3fc" }}
            onClick={() => setMiExpanded(!miExpanded)}
          >
            <div className="flex items-center gap-4 flex-wrap">
              <h2 className="text-2xl font-bold text-[#252525]">🌐 Market Analysis (MA)</h2>
              {stanceBadge(miResult.overall_stance)}
              {miResult.cached && (
                <span className="text-xs text-gray-400 font-medium">cached</span>
              )}
              {miResult.fetched_at && (
                <span className="text-gray-400 text-xs">
                  {new Date(miResult.fetched_at).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}
                </span>
              )}
            </div>
            <span className="text-gray-400 text-sm">{miExpanded ? T("panel_collapse") : T("panel_expand")}</span>
          </button>

          {miExpanded && (
            <div className="px-8 py-6">
              {/* Quick summary bullets if available */}
              {(miResult.macro_themes.length > 0 || miResult.black_swans.length > 0) && (
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-6">
                  {miResult.macro_themes.length > 0 && (
                    <div
                      className="rounded-xl p-4"
                      style={{ background: "#f0f9ff", border: "1px solid #bae6fd" }}
                    >
                      <p className="text-xs font-bold text-sky-700 uppercase tracking-wide mb-2">🌍 Macro Themes</p>
                      <ul className="space-y-1">
                        {miResult.macro_themes.slice(0, 4).map((t, i) => (
                          <li key={i} className="text-xs text-sky-900 flex gap-1.5">
                            <span className="text-sky-400 flex-shrink-0">•</span>
                            <span>{t}</span>
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}
                  {miResult.black_swans.length > 0 && (
                    <div
                      className="rounded-xl p-4"
                      style={{ background: "#fff1f2", border: "1px solid #fecdd3" }}
                    >
                      <p className="text-xs font-bold text-red-700 uppercase tracking-wide mb-2">🦢 Black Swans</p>
                      <ul className="space-y-1">
                        {miResult.black_swans.slice(0, 4).map((t, i) => (
                          <li key={i} className="text-xs text-red-900 flex gap-1.5">
                            <span className="text-red-400 flex-shrink-0">•</span>
                            <span>{t}</span>
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}
                </div>
              )}

              {/* Full analyst note */}
              <div className="text-sm text-gray-700 leading-relaxed">
                <SimpleMarkdown>{miResult.intel_markdown}</SimpleMarkdown>
              </div>

              {/* Sources crawled + refresh + provenance */}
              <div className="mt-5 pt-4 border-t border-gray-100 space-y-2">
                {miResult.sources_used && miResult.sources_used.length > 0 && (
                  <div className="flex items-start gap-2 flex-wrap">
                    <span className="text-xs font-semibold text-cyan-700 whitespace-nowrap">🌊 Sources crawled:</span>
                    <div className="flex flex-wrap gap-1">
                      {miResult.sources_used.map((src) => (
                        <span key={src} className="text-xs px-2 py-0.5 rounded-full font-medium"
                          style={{ background: "#ecfeff", color: "#0e7490", border: "1px solid #a5f3fc" }}>
                          {src}
                        </span>
                      ))}
                    </div>
                  </div>
                )}
                <div className="flex items-center gap-2 flex-wrap text-xs text-gray-300">
                  <span
                    className="font-bold text-cyan-600 cursor-pointer hover:text-cyan-700"
                    onClick={() => runMarketIntel(true)}
                    title="Re-crawl all sources"
                  >
                    ↻ Refresh
                  </span>
                  <span>→ Senior investment bank analyst synthesis</span>
                  <span className="ml-auto italic">{T("panel_not_advice")}</span>
                </div>
              </div>
            </div>
          )}
        </div>
      )}

      {/* ── ASX Trading Signal result panel ─────────────────────────────────── */}
      {asxPhase === "done" && asxResult && (
        <div className="bg-white border border-gray-200 rounded-2xl shadow-sm overflow-hidden">
          <button
            className="w-full px-8 py-5 flex items-center justify-between border-b border-gray-100 text-left hover:bg-gray-50 transition-colors"
            onClick={() => setAsxExpanded(!asxExpanded)}
          >
            <div className="flex items-center gap-4 flex-wrap">
              <h2 className="text-2xl font-bold text-[#252525]">{T("panel_asx_title")}</h2>
              {signalBadge(asxResult.signal_markdown)}
              {asxResult.current_price && (
                <span className="text-gray-500 text-sm font-medium">
                  A${asxResult.current_price.toFixed(2)}
                </span>
              )}
            </div>
            <span className="text-gray-400 text-sm">{asxExpanded ? T("panel_collapse") : T("panel_expand")}</span>
          </button>
          {asxExpanded && (
            <div className="px-8 py-6">
              <div className="mb-4 p-3 rounded-lg bg-amber-50 border border-amber-100 text-xs text-amber-700">
                {T("panel_asx_notice")}
              </div>
              <div className="text-sm text-gray-700 leading-relaxed">
                <SimpleMarkdown>{asxResult.signal_markdown}</SimpleMarkdown>
              </div>
              {/* Data provenance trail — TinyFish IR scan is the unique input */}
              <div className="mt-5 pt-4 border-t border-gray-100 flex items-center gap-2 flex-wrap text-xs text-gray-300">
                <span className="font-semibold text-green-600">🌊 TinyFish IR scan</span>
                <span>→ language change detection</span>
                <span>→ Yahoo Finance ASX price (multi-timeframe)</span>
                <span>→ Gemini (Google Search grounded)</span>
                <span className="ml-auto italic">{T("panel_not_advice")}</span>
              </div>
            </div>
          )}
        </div>
      )}

      {/* ── Chart Analysis (CA) inline result panel ─────────────────────────── */}
      {chartPhase === "done" && chartResult && (
        <div
          className="bg-white rounded-2xl shadow-sm overflow-hidden"
          style={{ border: "2px solid #a5b4fc" }}
        >
          <button
            className="w-full px-8 py-5 flex items-center justify-between border-b text-left hover:bg-indigo-50/50 transition-colors"
            style={{ borderBottomColor: "#c7d2fe" }}
            onClick={() => setChartExpanded(!chartExpanded)}
          >
            <div className="flex items-center gap-4 flex-wrap">
              <h2 className="text-2xl font-bold text-[#252525]">💬 Chart Analysis (CA)</h2>
              {chartFromCache && (
                <span className="text-xs text-gray-400 font-medium">cached</span>
              )}
              <button
                className="text-xs font-semibold px-3 py-1 rounded-full transition-colors"
                style={{ background: "#ede9fe", color: "#6366f1", border: "1px solid #a5b4fc" }}
                onClick={(e) => { e.stopPropagation(); setShowModal(true); }}
              >
                🔍 View Full Chart
              </button>
            </div>
            <span className="text-gray-400 text-sm">{chartExpanded ? T("panel_collapse") : T("panel_expand")}</span>
          </button>
          {chartExpanded && (
            <div className="px-8 py-6">
              {/* Chart thumbnail */}
              {chartResult.chart_b64 && (
                <div className="mb-5 cursor-pointer" onClick={() => setShowModal(true)}>
                  {/* eslint-disable-next-line @next/next/no-img-element */}
                  <img
                    src={`data:image/png;base64,${chartResult.chart_b64}`}
                    alt="Technical analysis chart"
                    className="w-full rounded-xl hover:opacity-90 transition-opacity"
                    style={{ border: "1px solid #e5e7eb", maxHeight: "400px", objectFit: "contain" }}
                  />
                </div>
              )}
              {/* Gemini analysis text */}
              <div className="text-sm text-gray-700 leading-relaxed">
                <SimpleMarkdown>{chartResult.analysis}</SimpleMarkdown>
              </div>
              {/* Data provenance trail */}
              <div className="mt-5 pt-4 border-t border-gray-100 flex items-center gap-2 flex-wrap text-xs text-gray-300">
                <span className="font-semibold text-indigo-500">🌊 TinyFish</span>
                <span>→ Yahoo Finance OHLCV</span>
                <span>→ 3-panel chart render</span>
                <span>→ Gemini Vision pattern recognition</span>
                <span
                  className="font-bold text-indigo-500 cursor-pointer hover:text-indigo-600 ml-2"
                  onClick={() => runChartAnalysis(true)}
                  title="Re-generate chart analysis"
                >
                  ↻ Refresh
                </span>
                <span className="ml-auto italic">{T("panel_not_advice")}</span>
              </div>
            </div>
          )}
        </div>
      )}

      {/* ── Chart Vision modal ───────────────────────────────────────────────── */}
      {showModal && chartResult && (
        <ChartModal chart={chartResult} onClose={() => setShowModal(false)} lang={lang} />
      )}
    </div>
  );
}
