-- Homepage landing page i18n labels
INSERT INTO datapai.sys_lang_labels (label_key, lang, text, category) VALUES
-- Hero
('home_hero_headline', 'en', 'AI-Powered Stock Intelligence Across Asia-Pacific', 'home'),
('home_hero_sub', 'en', '12 markets. 50,000+ stocks. 8 languages. Powered by AI agents that never sleep.', 'home'),
('home_cta_start', 'en', 'Get Started Free', 'home'),
('home_cta_explore', 'en', 'Explore Markets', 'home'),
-- Markets
('home_markets_title', 'en', 'From Wall Street to Southeast Asia', 'home'),
('home_markets_sub', 'en', 'Every market, one platform. Real-time prices, AI analysis, and alerts.', 'home'),
('home_stocks', 'en', 'stocks', 'home'),
-- Features
('home_features_title', 'en', 'What Makes Us Different', 'home'),
('home_features_sub', 'en', 'AI agents that read company websites, debate each other, and deliver verified signals.', 'home'),
('home_feat_tinyfish_title', 'en', 'Website Intelligence', 'home'),
('home_feat_tinyfish_desc', 'en', 'Real browser agents visit company IR pages before announcements hit the exchange. Detect guidance changes, risk disclosures, and tone shifts — hours before the market reacts.', 'home'),
('home_feat_multiagent_title', 'en', 'Multi-Agent AI Debate', 'home'),
('home_feat_multiagent_desc', 'en', 'Not one AI — a team. Multiple agents analyse independently, debate each other, and cross-validate. Only the consensus survives. Like a room of analysts arguing your trade.', 'home'),
('home_feat_copilot_title', 'en', 'AI Copilot', 'home'),
('home_feat_copilot_desc', 'en', 'Ask anything about any stock, in your language. Context-aware — knows what page you are on, what stocks you hold, and your risk profile.', 'home'),
('home_feat_screener_title', 'en', 'AI Screener', 'home'),
('home_feat_screener_desc', 'en', '50,000+ stocks scored daily. BUY/SELL signals across 4 timeframes. Technical + fundamental + website intelligence combined into one score.', 'home'),
('home_feat_studio_title', 'en', 'Custom AI Studio', 'home'),
('home_feat_studio_desc', 'en', 'Build your own AI strategy. Define rules, backtest with 5 years of data, let AI run it automatically. Your strategy, your edge.', 'home'),
('home_feat_verify_title', 'en', 'Multi-Source Verification', 'home'),
('home_feat_verify_desc', 'en', 'Every signal cross-validated across company websites, exchange filings, press releases, and news. Confidence scores, not guesses.', 'home'),
-- Pipeline
('home_pipeline_title', 'en', 'How AI Agents Work Together', 'home'),
('home_pipeline_sub', 'en', 'Multiple agents analyse independently, then validate each other. Only verified signals reach you.', 'home'),
('home_pipeline_parallel', 'en', '3 agents in parallel', 'home'),
('home_pipeline_output', 'en', 'Verified output', 'home'),
-- How it works
('home_how_title', 'en', 'How It Works', 'home'),
('home_how_1_title', 'en', 'Pick Your Markets', 'home'),
('home_how_1_desc', 'en', 'Choose from 12 exchanges. Add stocks to your watchlist. Set your risk profile and preferred language.', 'home'),
('home_how_2_title', 'en', 'AI Does The Research', 'home'),
('home_how_2_desc', 'en', 'AI agents scan company websites, analyse technicals, score fundamentals, and debate each other — 24/7.', 'home'),
('home_how_3_title', 'en', 'You Make The Call', 'home'),
('home_how_3_desc', 'en', 'Get BUY/SELL signals with confidence scores. Ask the AI copilot to explain. The decision is always yours.', 'home'),
-- Language
('home_lang_title', 'en', 'Speak Your Language', 'home'),
('home_lang_sub', 'en', 'Every AI report, signal, and chat — in your preferred language.', 'home'),
-- Powered by
('home_powered_by', 'en', 'Powered By', 'home'),
-- Pricing
('home_pricing_title', 'en', 'Free Forever to Start', 'home'),
('home_pricing_sub', 'en', 'No credit card required. Upgrade when you are ready for more AI signals, larger watchlists, and custom strategies.', 'home'),
('home_pricing_free', 'en', 'Signal Watch — Free forever', 'home'),
('home_pricing_individual', 'en', 'Individual — Full AI suite', 'home'),
('home_pricing_pro', 'en', 'Professional — All markets', 'home'),
('home_pricing_cta', 'en', 'View all plans', 'home'),
-- Final CTA
('home_final_title', 'en', '50,000+ Stocks Monitored by AI. Start Free Today.', 'home'),
('home_final_sub', 'en', 'Join investors across Asia-Pacific using AI to find opportunities faster.', 'home'),
('home_final_cta', 'en', 'Create Free Account', 'home'),

-- Simplified Chinese
('home_hero_headline', 'zh', 'AI驱动的亚太股市智能分析平台', 'home'),
('home_hero_sub', 'zh', '12个市场 · 50,000+股票 · 8种语言 · AI代理全天候运行', 'home'),
('home_cta_start', 'zh', '免费开始', 'home'),
('home_cta_explore', 'zh', '探索市场', 'home'),
('home_markets_title', 'zh', '从华尔街到东南亚', 'home'),
('home_markets_sub', 'zh', '全球市场,一个平台。实时价格、AI分析和警报。', 'home'),
('home_stocks', 'zh', '只股票', 'home'),
('home_features_title', 'zh', '我们的独特优势', 'home'),
('home_features_sub', 'zh', 'AI代理阅读公司网站、互相辩论、交付验证信号。', 'home'),
('home_feat_tinyfish_title', 'zh', '网站情报', 'home'),
('home_feat_tinyfish_desc', 'zh', '真实浏览器代理在公告发布前访问公司IR页面。检测指引变化、风险披露和语气转变——领先市场数小时。', 'home'),
('home_feat_multiagent_title', 'zh', '多代理AI辩论', 'home'),
('home_feat_multiagent_desc', 'zh', '不是一个AI——而是一个团队。多个代理独立分析、互相辩论、交叉验证。只有共识才能通过。', 'home'),
('home_feat_copilot_title', 'zh', 'AI助手', 'home'),
('home_feat_copilot_desc', 'zh', '用您的语言询问任何股票的任何问题。上下文感知——了解您所在的页面、持仓和风险偏好。', 'home'),
('home_feat_screener_title', 'zh', 'AI选股器', 'home'),
('home_feat_screener_desc', 'zh', '每日评估50,000+股票。4个时间维度的买卖信号。技术面+基本面+网站情报综合评分。', 'home'),
('home_feat_studio_title', 'zh', '自定义AI工作室', 'home'),
('home_feat_studio_desc', 'zh', '构建您自己的AI策略。定义规则、用5年数据回测、让AI自动执行。您的策略,您的优势。', 'home'),
('home_feat_verify_title', 'zh', '多源验证', 'home'),
('home_feat_verify_desc', 'zh', '每个信号都经过公司网站、交易所文件、新闻稿和新闻的交叉验证。置信度评分,而非猜测。', 'home'),
('home_pipeline_title', 'zh', 'AI代理如何协作', 'home'),
('home_pipeline_sub', 'zh', '多个代理独立分析,然后互相验证。只有经过验证的信号才会传达给您。', 'home'),
('home_pipeline_parallel', 'zh', '3个代理并行', 'home'),
('home_pipeline_output', 'zh', '验证输出', 'home'),
('home_how_title', 'zh', '如何使用', 'home'),
('home_how_1_title', 'zh', '选择市场', 'home'),
('home_how_1_desc', 'zh', '从12个交易所中选择。将股票添加到您的自选股。设置风险偏好和语言。', 'home'),
('home_how_2_title', 'zh', 'AI进行研究', 'home'),
('home_how_2_desc', 'zh', 'AI代理扫描公司网站、分析技术面、评估基本面、互相辩论——全天候运行。', 'home'),
('home_how_3_title', 'zh', '您做决定', 'home'),
('home_how_3_desc', 'zh', '获取带有置信度评分的买卖信号。向AI助手提问。决定权始终在您。', 'home'),
('home_lang_title', 'zh', '说您的语言', 'home'),
('home_lang_sub', 'zh', '每份AI报告、信号和对话——都使用您的首选语言。', 'home'),
('home_powered_by', 'zh', '技术支持', 'home'),
('home_pricing_title', 'zh', '免费开始,永久免费', 'home'),
('home_pricing_sub', 'zh', '无需信用卡。准备好后再升级获取更多AI信号、更大的自选股列表和自定义策略。', 'home'),
('home_pricing_free', 'zh', '信号观察 — 永久免费', 'home'),
('home_pricing_individual', 'zh', '个人版 — 完整AI套件', 'home'),
('home_pricing_pro', 'zh', '专业版 — 全市场覆盖', 'home'),
('home_pricing_cta', 'zh', '查看所有方案', 'home'),
('home_final_title', 'zh', '50,000+股票由AI监控。今天免费开始。', 'home'),
('home_final_sub', 'zh', '加入亚太地区使用AI更快发现机会的投资者。', 'home'),
('home_final_cta', 'zh', '创建免费账户', 'home'),

-- Traditional Chinese
('home_hero_headline', 'zh-TW', 'AI驅動的亞太股市智慧分析平台', 'home'),
('home_hero_sub', 'zh-TW', '12個市場 · 50,000+股票 · 8種語言 · AI代理全天候運行', 'home'),
('home_cta_start', 'zh-TW', '免費開始', 'home'),
('home_cta_explore', 'zh-TW', '探索市場', 'home'),
('home_markets_title', 'zh-TW', '從華爾街到東南亞', 'home'),
('home_markets_sub', 'zh-TW', '全球市場,一個平台。即時價格、AI分析和警報。', 'home'),
('home_stocks', 'zh-TW', '檔股票', 'home'),
('home_features_title', 'zh-TW', '我們的獨特優勢', 'home'),
('home_features_sub', 'zh-TW', 'AI代理閱讀公司網站、互相辯論、交付驗證信號。', 'home'),
('home_feat_tinyfish_title', 'zh-TW', '網站情報', 'home'),
('home_feat_tinyfish_desc', 'zh-TW', '真實瀏覽器代理在公告發佈前訪問公司IR頁面。檢測指引變化、風險披露和語氣轉變——領先市場數小時。', 'home'),
('home_feat_multiagent_title', 'zh-TW', '多代理AI辯論', 'home'),
('home_feat_multiagent_desc', 'zh-TW', '不是一個AI——而是一個團隊。多個代理獨立分析、互相辯論、交叉驗證。只有共識才能通過。', 'home'),
('home_how_title', 'zh-TW', '如何使用', 'home'),
('home_how_1_title', 'zh-TW', '選擇市場', 'home'),
('home_how_2_title', 'zh-TW', 'AI進行研究', 'home'),
('home_how_3_title', 'zh-TW', '您做決定', 'home'),
('home_lang_title', 'zh-TW', '說您的語言', 'home'),
('home_pricing_title', 'zh-TW', '免費開始,永久免費', 'home'),
('home_final_title', 'zh-TW', '50,000+股票由AI監控。今天免費開始。', 'home'),
('home_final_cta', 'zh-TW', '建立免費帳戶', 'home'),

-- Japanese
('home_hero_headline', 'ja', 'AIが駆動するアジア太平洋の株式インテリジェンス', 'home'),
('home_hero_sub', 'ja', '12市場 · 50,000+銘柄 · 8言語対応 · AIエージェントが24時間稼働', 'home'),
('home_cta_start', 'ja', '無料で始める', 'home'),
('home_cta_explore', 'ja', '市場を探索', 'home'),
('home_markets_title', 'ja', 'ウォール街から東南アジアまで', 'home'),
('home_stocks', 'ja', '銘柄', 'home'),
('home_features_title', 'ja', '他にない強み', 'home'),
('home_feat_tinyfish_title', 'ja', 'ウェブサイトインテリジェンス', 'home'),
('home_feat_multiagent_title', 'ja', 'マルチエージェントAI討論', 'home'),
('home_feat_copilot_title', 'ja', 'AIコパイロット', 'home'),
('home_feat_screener_title', 'ja', 'AIスクリーナー', 'home'),
('home_feat_studio_title', 'ja', 'カスタムAIスタジオ', 'home'),
('home_feat_verify_title', 'ja', '多元検証', 'home'),
('home_how_title', 'ja', '使い方', 'home'),
('home_how_1_title', 'ja', '市場を選ぶ', 'home'),
('home_how_2_title', 'ja', 'AIがリサーチ', 'home'),
('home_how_3_title', 'ja', 'あなたが判断', 'home'),
('home_lang_title', 'ja', 'あなたの言語で', 'home'),
('home_pricing_title', 'ja', '永久無料プランから始める', 'home'),
('home_final_title', 'ja', 'AIが50,000+銘柄を監視。今日から無料で。', 'home'),
('home_final_cta', 'ja', '無料アカウント作成', 'home'),

-- Vietnamese
('home_hero_headline', 'vi', 'Trí tuệ nhân tạo phân tích chứng khoán Châu Á - Thái Bình Dương', 'home'),
('home_cta_start', 'vi', 'Bắt đầu miễn phí', 'home'),
('home_markets_title', 'vi', 'Từ Wall Street đến Đông Nam Á', 'home'),
('home_stocks', 'vi', 'cổ phiếu', 'home'),
('home_features_title', 'vi', 'Điểm khác biệt của chúng tôi', 'home'),
('home_how_title', 'vi', 'Cách hoạt động', 'home'),
('home_lang_title', 'vi', 'Nói ngôn ngữ của bạn', 'home'),
('home_pricing_title', 'vi', 'Miễn phí mãi mãi để bắt đầu', 'home'),
('home_final_cta', 'vi', 'Tạo tài khoản miễn phí', 'home'),

-- Thai
('home_hero_headline', 'th', 'ระบบวิเคราะห์หุ้นด้วย AI ครอบคลุมเอเชียแปซิฟิก', 'home'),
('home_cta_start', 'th', 'เริ่มต้นฟรี', 'home'),
('home_stocks', 'th', 'หุ้น', 'home'),
('home_features_title', 'th', 'สิ่งที่ทำให้เราแตกต่าง', 'home'),
('home_how_title', 'th', 'วิธีการทำงาน', 'home'),
('home_final_cta', 'th', 'สร้างบัญชีฟรี', 'home'),

-- Korean
('home_hero_headline', 'ko', 'AI 기반 아시아태평양 주식 인텔리전스', 'home'),
('home_cta_start', 'ko', '무료로 시작', 'home'),
('home_stocks', 'ko', '종목', 'home'),
('home_features_title', 'ko', '우리만의 차별화', 'home'),
('home_how_title', 'ko', '이용 방법', 'home'),
('home_final_cta', 'ko', '무료 계정 만들기', 'home'),

-- Malay
('home_hero_headline', 'ms', 'Kecerdasan Saham Dikuasakan AI Merentasi Asia-Pasifik', 'home'),
('home_cta_start', 'ms', 'Mula Percuma', 'home'),
('home_stocks', 'ms', 'saham', 'home'),
('home_features_title', 'ms', 'Apa Yang Membezakan Kami', 'home'),
('home_how_title', 'ms', 'Cara Ia Berfungsi', 'home'),
('home_final_cta', 'ms', 'Cipta Akaun Percuma', 'home')

ON CONFLICT (label_key, lang) DO UPDATE SET text = EXCLUDED.text, category = EXCLUDED.category;
