-- Migration 028: i18n labels for /why-datapai page
-- All 8 languages: en, zh, zh-TW, vi, th, ms, ja, ko

INSERT INTO datapai.sys_lang_labels (label_key, lang, text, category) VALUES

-- ── Nav ──
('nav_why_us', 'en', 'Why DataP.ai', 'nav'),
('nav_why_us', 'zh', '为什么选择DataP.ai', 'nav'),
('nav_why_us', 'zh-TW', '為什麼選擇DataP.ai', 'nav'),
('nav_why_us', 'vi', 'Tại sao DataP.ai', 'nav'),
('nav_why_us', 'th', 'ทำไมต้อง DataP.ai', 'nav'),
('nav_why_us', 'ms', 'Mengapa DataP.ai', 'nav'),
('nav_why_us', 'ja', 'DataP.aiを選ぶ理由', 'nav'),
('nav_why_us', 'ko', 'DataP.ai를 선택하는 이유', 'nav'),

-- ── Hero ──
('why_hero_label', 'en', 'Why DataP.ai', 'why'),
('why_hero_label', 'zh', '为什么选择 DataP.ai', 'why'),
('why_hero_label', 'zh-TW', '為什麼選擇 DataP.ai', 'why'),
('why_hero_label', 'vi', 'Tại sao chọn DataP.ai', 'why'),
('why_hero_label', 'th', 'ทำไมต้อง DataP.ai', 'why'),
('why_hero_label', 'ms', 'Mengapa DataP.ai', 'why'),
('why_hero_label', 'ja', 'なぜ DataP.ai なのか', 'why'),
('why_hero_label', 'ko', '왜 DataP.ai인가', 'why'),

('why_hero_headline', 'en', 'AI Stock Research That Gets The Numbers Right', 'why'),
('why_hero_headline', 'zh', '准确可靠的AI股票研究', 'why'),
('why_hero_headline', 'zh-TW', '準確可靠的AI股票研究', 'why'),
('why_hero_headline', 'vi', 'Nghien cuu co phieu AI chinh xac den tung con so', 'why'),
('why_hero_headline', 'th', 'วิจัยหุ้น AI ที่ให้ตัวเลขถูกต้อง', 'why'),
('why_hero_headline', 'ms', 'Penyelidikan Saham AI Yang Tepat', 'why'),
('why_hero_headline', 'ja', '正確な数字を提供するAI株式リサーチ', 'why'),
('why_hero_headline', 'ko', '정확한 숫자를 제공하는 AI 주식 리서치', 'why'),

('why_hero_sub', 'en', '13 markets. 8 native languages. Real-time OHLCV data verified against Google Finance.', 'why'),
('why_hero_sub', 'zh', '13个市场。8种母语。实时OHLCV数据与Google Finance验证一致。', 'why'),
('why_hero_sub', 'zh-TW', '13個市場。8種母語。即時OHLCV數據與Google Finance驗證一致。', 'why'),
('why_hero_sub', 'vi', '13 thi truong. 8 ngon ngu ban dia. Du lieu OHLCV thoi gian thuc da xac minh voi Google Finance.', 'why'),
('why_hero_sub', 'th', '13 ตลาด 8 ภาษา ข้อมูล OHLCV เรียลไทม์ตรวจสอบกับ Google Finance', 'why'),
('why_hero_sub', 'ms', '13 pasaran. 8 bahasa. Data OHLCV masa nyata disahkan dengan Google Finance.', 'why'),
('why_hero_sub', 'ja', '13市場。8言語。Google Financeで検証済みのリアルタイムOHLCVデータ。', 'why'),
('why_hero_sub', 'ko', '13개 시장. 8개 언어. Google Finance와 검증된 실시간 OHLCV 데이터.', 'why'),

('why_audience_investors', 'en', 'Self-Directed Investors', 'why'),
('why_audience_investors', 'zh', '自主投资者', 'why'),
('why_audience_investors', 'zh-TW', '自主投資者', 'why'),
('why_audience_investors', 'vi', 'Nha dau tu tu chu', 'why'),
('why_audience_investors', 'th', 'นักลงทุนอิสระ', 'why'),
('why_audience_investors', 'ms', 'Pelabur Bebas', 'why'),
('why_audience_investors', 'ja', '個人投資家', 'why'),
('why_audience_investors', 'ko', '자기주도 투자자', 'why'),

('why_audience_partners', 'en', 'Broker Partners', 'why'),
('why_audience_partners', 'zh', '券商合作伙伴', 'why'),
('why_audience_partners', 'zh-TW', '券商合作夥伴', 'why'),
('why_audience_partners', 'vi', 'Doi tac moi gioi', 'why'),
('why_audience_partners', 'th', 'พาร์ทเนอร์โบรกเกอร์', 'why'),
('why_audience_partners', 'ms', 'Rakan Broker', 'why'),
('why_audience_partners', 'ja', 'ブローカーパートナー', 'why'),
('why_audience_partners', 'ko', '브로커 파트너', 'why'),

('why_audience_vcs', 'en', 'Investors & VCs', 'why'),
('why_audience_vcs', 'zh', '投资人与风投', 'why'),
('why_audience_vcs', 'zh-TW', '投資人與風投', 'why'),
('why_audience_vcs', 'vi', 'Nha dau tu & VC', 'why'),
('why_audience_vcs', 'th', 'นักลงทุน & VC', 'why'),
('why_audience_vcs', 'ms', 'Pelabur & VC', 'why'),
('why_audience_vcs', 'ja', '投資家 & VC', 'why'),
('why_audience_vcs', 'ko', '투자자 & VC', 'why'),

-- ── Accuracy Challenge ──
('why_accuracy_title', 'en', 'The Price Accuracy Challenge', 'why'),
('why_accuracy_title', 'zh', '价格准确性挑战', 'why'),
('why_accuracy_title', 'zh-TW', '價格準確性挑戰', 'why'),
('why_accuracy_title', 'vi', 'Thach thuc do chinh xac gia', 'why'),
('why_accuracy_title', 'th', 'ความท้าทายด้านความแม่นยำของราคา', 'why'),
('why_accuracy_title', 'ms', 'Cabaran Ketepatan Harga', 'why'),
('why_accuracy_title', 'ja', '価格精度チャレンジ', 'why'),
('why_accuracy_title', 'ko', '가격 정확도 챌린지', 'why'),

('why_accuracy_sub', 'en', 'We asked 3 AI assistants the same question: "What is the current price of BHP on ASX?" Here are the results.', 'why'),
('why_accuracy_sub', 'zh', '我们向3个AI助手问了同一个问题："BHP在ASX的当前价格是多少？"以下是结果。', 'why'),
('why_accuracy_sub', 'zh-TW', '我們向3個AI助手問了同一個問題：「BHP在ASX的當前價格是多少？」以下是結果。', 'why'),
('why_accuracy_sub', 'vi', 'Chung toi da hoi 3 tro ly AI cung mot cau hoi: "Gia hien tai cua BHP tren ASX la bao nhieu?" Day la ket qua.', 'why'),
('why_accuracy_sub', 'th', 'เราถามผู้ช่วย AI 3 ตัวด้วยคำถามเดียวกัน: "ราคาปัจจุบันของ BHP บน ASX คือเท่าไร?" นี่คือผลลัพธ์', 'why'),
('why_accuracy_sub', 'ms', 'Kami bertanya 3 pembantu AI soalan yang sama: "Berapakah harga semasa BHP di ASX?" Ini hasilnya.', 'why'),
('why_accuracy_sub', 'ja', '3つのAIアシスタントに同じ質問をしました：「ASXでのBHPの現在の価格は？」結果はこちら。', 'why'),
('why_accuracy_sub', 'ko', '3개의 AI 어시스턴트에게 같은 질문을 했습니다: "ASX에서 BHP의 현재 가격은?" 결과는 다음과 같습니다.', 'why'),

('why_cmp_metric', 'en', 'Metric', 'why'),
('why_cmp_metric', 'zh', '指标', 'why'),
('why_cmp_metric', 'zh-TW', '指標', 'why'),
('why_cmp_metric', 'vi', 'Chi so', 'why'),
('why_cmp_metric', 'th', 'ตัวชี้วัด', 'why'),
('why_cmp_metric', 'ms', 'Metrik', 'why'),
('why_cmp_metric', 'ja', '指標', 'why'),
('why_cmp_metric', 'ko', '지표', 'why'),

('why_cmp_competitor_a', 'en', 'Leading Trading App AI', 'why'),
('why_cmp_competitor_a', 'zh', '领先交易应用AI', 'why'),
('why_cmp_competitor_a', 'zh-TW', '領先交易應用AI', 'why'),
('why_cmp_competitor_a', 'vi', 'AI ung dung giao dich hang dau', 'why'),
('why_cmp_competitor_a', 'th', 'AI แอปเทรดชั้นนำ', 'why'),
('why_cmp_competitor_a', 'ms', 'AI Aplikasi Dagangan Terkemuka', 'why'),
('why_cmp_competitor_a', 'ja', '大手取引アプリAI', 'why'),
('why_cmp_competitor_a', 'ko', '선도적 트레이딩 앱 AI', 'why'),

('why_cmp_competitor_b', 'en', 'Leading AI Assistant', 'why'),
('why_cmp_competitor_b', 'zh', '领先AI助手', 'why'),
('why_cmp_competitor_b', 'zh-TW', '領先AI助手', 'why'),
('why_cmp_competitor_b', 'vi', 'Tro ly AI hang dau', 'why'),
('why_cmp_competitor_b', 'th', 'AI ผู้ช่วยชั้นนำ', 'why'),
('why_cmp_competitor_b', 'ms', 'Pembantu AI Terkemuka', 'why'),
('why_cmp_competitor_b', 'ja', '大手AIアシスタント', 'why'),
('why_cmp_competitor_b', 'ko', '선도적 AI 어시스턴트', 'why'),

('why_cmp_price', 'en', 'BHP Close Price (actual: $52.56)', 'why'),
('why_cmp_price', 'zh', 'BHP收盘价（实际: $52.56）', 'why'),
('why_cmp_price', 'zh-TW', 'BHP收盤價（實際: $52.56）', 'why'),
('why_cmp_price', 'vi', 'Gia dong cua BHP (thuc te: $52.56)', 'why'),
('why_cmp_price', 'th', 'ราคาปิด BHP (จริง: $52.56)', 'why'),
('why_cmp_price', 'ms', 'Harga Penutup BHP (sebenar: $52.56)', 'why'),
('why_cmp_price', 'ja', 'BHP終値（実際: $52.56）', 'why'),
('why_cmp_price', 'ko', 'BHP 종가 (실제: $52.56)', 'why'),

('why_cmp_ohlcv', 'en', 'OHLCV Data (vs Google Finance)', 'why'),
('why_cmp_ohlcv', 'zh', 'OHLCV数据（对比Google Finance）', 'why'),
('why_cmp_ohlcv', 'zh-TW', 'OHLCV數據（對比Google Finance）', 'why'),
('why_cmp_ohlcv', 'vi', 'Du lieu OHLCV (so voi Google Finance)', 'why'),
('why_cmp_ohlcv', 'th', 'ข้อมูล OHLCV (เทียบกับ Google Finance)', 'why'),
('why_cmp_ohlcv', 'ms', 'Data OHLCV (vs Google Finance)', 'why'),
('why_cmp_ohlcv', 'ja', 'OHLCVデータ（Google Finance対比）', 'why'),
('why_cmp_ohlcv', 'ko', 'OHLCV 데이터 (Google Finance 대비)', 'why'),

('why_cmp_lang', 'en', 'Native Language Support', 'why'),
('why_cmp_lang', 'zh', '母语支持', 'why'),
('why_cmp_lang', 'zh-TW', '母語支持', 'why'),
('why_cmp_lang', 'vi', 'Ho tro ngon ngu ban dia', 'why'),
('why_cmp_lang', 'th', 'รองรับภาษาท้องถิ่น', 'why'),
('why_cmp_lang', 'ms', 'Sokongan Bahasa Tempatan', 'why'),
('why_cmp_lang', 'ja', 'ネイティブ言語サポート', 'why'),
('why_cmp_lang', 'ko', '현지 언어 지원', 'why'),

('why_cmp_timezone', 'en', 'Local Timezone Display', 'why'),
('why_cmp_timezone', 'zh', '本地时区显示', 'why'),
('why_cmp_timezone', 'zh-TW', '本地時區顯示', 'why'),
('why_cmp_timezone', 'vi', 'Hien thi mui gio dia phuong', 'why'),
('why_cmp_timezone', 'th', 'แสดงเขตเวลาท้องถิ่น', 'why'),
('why_cmp_timezone', 'ms', 'Paparan Zon Waktu Tempatan', 'why'),
('why_cmp_timezone', 'ja', 'ローカルタイムゾーン表示', 'why'),
('why_cmp_timezone', 'ko', '현지 시간대 표시', 'why'),

('why_cmp_company', 'en', 'Company Name Translation', 'why'),
('why_cmp_company', 'zh', '公司名称翻译', 'why'),
('why_cmp_company', 'zh-TW', '公司名稱翻譯', 'why'),
('why_cmp_company', 'vi', 'Dich ten cong ty', 'why'),
('why_cmp_company', 'th', 'แปลชื่อบริษัท', 'why'),
('why_cmp_company', 'ms', 'Terjemahan Nama Syarikat', 'why'),
('why_cmp_company', 'ja', '企業名翻訳', 'why'),
('why_cmp_company', 'ko', '회사명 번역', 'why'),

('why_cmp_format', 'en', 'Response Format (concise vs verbose)', 'why'),
('why_cmp_format', 'zh', '回复格式（简洁 vs 冗长）', 'why'),
('why_cmp_format', 'zh-TW', '回覆格式（簡潔 vs 冗長）', 'why'),
('why_cmp_format', 'vi', 'Dinh dang phan hoi (ngan gon vs dai dong)', 'why'),
('why_cmp_format', 'th', 'รูปแบบคำตอบ (กระชับ vs ยืดยาว)', 'why'),
('why_cmp_format', 'ms', 'Format Respons (ringkas vs verbose)', 'why'),
('why_cmp_format', 'ja', '回答形式（簡潔 vs 冗長）', 'why'),
('why_cmp_format', 'ko', '응답 형식 (간결 vs 장황)', 'why'),

('why_cmp_price_shown', 'en', 'Price shown', 'why'),
('why_cmp_price_shown', 'zh', '显示价格', 'why'),
('why_cmp_response_style', 'en', 'Response style', 'why'),
('why_cmp_response_style', 'zh', '回复风格', 'why'),
('why_cmp_2lines', 'en', '2-line snapshot', 'why'),
('why_cmp_2lines', 'zh', '2行快照', 'why'),
('why_cmp_wall', 'en', 'Wall of text', 'why'),
('why_cmp_wall', 'zh', '大段文字', 'why'),
('why_cmp_verbose', 'en', 'Verbose essay', 'why'),
('why_cmp_verbose', 'zh', '冗长文章', 'why'),
('why_cmp_note', 'en', 'Test conducted April 2026. All AI assistants asked the same question about BHP on ASX. Competitor brands hidden.', 'why'),
('why_cmp_note', 'zh', '测试于2026年4月进行。所有AI助手被问了关于ASX上BHP的相同问题。竞品品牌已隐藏。', 'why'),

('why_ss_correct', 'en', 'Correct', 'why'),
('why_ss_correct', 'zh', '正确', 'why'),
('why_ss_wrong', 'en', 'Wrong', 'why'),
('why_ss_wrong', 'zh', '错误', 'why'),
('why_ss_wrong_ohlcv', 'en', 'Wrong OHLCV', 'why'),
('why_ss_wrong_ohlcv', 'zh', 'OHLCV错误', 'why'),
('why_ss_placeholder', 'en', 'Screenshot coming soon', 'why'),
('why_ss_placeholder', 'zh', '截图即将上线', 'why'),

-- ── Language Section ──
('why_lang_title', 'en', 'AI That Thinks In Your Language', 'why'),
('why_lang_title', 'zh', '用您的语言思考的AI', 'why'),
('why_lang_title', 'zh-TW', '用您的語言思考的AI', 'why'),
('why_lang_title', 'vi', 'AI suy nghi bang ngon ngu cua ban', 'why'),
('why_lang_title', 'th', 'AI ที่คิดเป็นภาษาของคุณ', 'why'),
('why_lang_title', 'ms', 'AI Yang Berfikir Dalam Bahasa Anda', 'why'),
('why_lang_title', 'ja', 'あなたの言語で考えるAI', 'why'),
('why_lang_title', 'ko', '당신의 언어로 생각하는 AI', 'why'),

('why_lang_sub', 'en', 'Not just translated UI. Company names, price labels, timezone, and disclaimer — all in your native language. No other AI stock platform does this.', 'why'),
('why_lang_sub', 'zh', '不仅是翻译界面。公司名称、价格标签、时区和免责声明——全部使用您的母语。没有其他AI股票平台能做到这一点。', 'why'),
('why_lang_sub', 'zh-TW', '不僅是翻譯界面。公司名稱、價格標籤、時區和免責聲明——全部使用您的母語。沒有其他AI股票平台能做到這一點。', 'why'),
('why_lang_sub', 'vi', 'Khong chi la giao dien dich. Ten cong ty, nhan gia, mui gio va tuyen bo mien tru — tat ca bang ngon ngu me de cua ban.', 'why'),
('why_lang_sub', 'th', 'ไม่ใช่แค่ UI ที่แปล ชื่อบริษัท ป้ายราคา เขตเวลา และข้อจำกัดความรับผิดชอบ — ทั้งหมดในภาษาแม่ของคุณ', 'why'),
('why_lang_sub', 'ms', 'Bukan sekadar UI yang diterjemahkan. Nama syarikat, label harga, zon masa dan penafian — semuanya dalam bahasa ibunda anda.', 'why'),
('why_lang_sub', 'ja', '単なるUI翻訳ではありません。企業名、価格ラベル、タイムゾーン、免責事項 — すべてネイティブ言語で。他のAI株式プラットフォームにはできません。', 'why'),
('why_lang_sub', 'ko', '단순한 UI 번역이 아닙니다. 회사명, 가격 라벨, 시간대, 면책조항 — 모두 모국어로. 다른 AI 주식 플랫폼은 이렇게 할 수 없습니다.', 'why'),

('why_lang_callout_title', 'en', '8 Languages, 100% Native', 'why'),
('why_lang_callout_title', 'zh', '8种语言，100%母语', 'why'),
('why_lang_callout_desc', 'en', 'English, Simplified Chinese, Traditional Chinese, Japanese, Korean, Vietnamese, Thai, Malay. Every label, every company name, every timestamp — translated from our proprietary stock dictionary covering 50,000+ stocks.', 'why'),
('why_lang_callout_desc', 'zh', '英语、简体中文、繁体中文、日语、韩语、越南语、泰语、马来语。每个标签、每个公司名称、每个时间戳——来自我们涵盖50,000+股票的专有股票词典。', 'why'),

-- ── Markets Section ──
('why_markets_title', 'en', '13 Markets. 50,000+ Stocks. One Platform.', 'why'),
('why_markets_title', 'zh', '13个市场。50,000+股票。一个平台。', 'why'),
('why_markets_title', 'zh-TW', '13個市場。50,000+股票。一個平台。', 'why'),
('why_markets_title', 'vi', '13 thi truong. 50,000+ co phieu. Mot nen tang.', 'why'),
('why_markets_title', 'th', '13 ตลาด 50,000+ หุ้น หนึ่งแพลตฟอร์ม', 'why'),
('why_markets_title', 'ms', '13 Pasaran. 50,000+ Saham. Satu Platform.', 'why'),
('why_markets_title', 'ja', '13市場。50,000+銘柄。ワンプラットフォーム。', 'why'),
('why_markets_title', 'ko', '13개 시장. 50,000+ 종목. 하나의 플랫폼.', 'why'),

('why_markets_sub', 'en', 'From Wall Street to Southeast Asia — the widest Asia-Pacific coverage of any AI stock platform.', 'why'),
('why_markets_sub', 'zh', '从华尔街到东南亚——所有AI股票平台中最广泛的亚太覆盖。', 'why'),
('why_markets_sub', 'vi', 'Tu Wall Street den Dong Nam A — pham vi bao phu Chau A-Thai Binh Duong rong nhat cua bat ky nen tang AI nao.', 'why'),
('why_markets_sub', 'ja', 'ウォール街から東南アジアまで — AIストックプラットフォーム最広のアジア太平洋カバレッジ。', 'why'),
('why_markets_sub', 'ko', '월스트리트에서 동남아시아까지 — AI 주식 플랫폼 중 가장 넓은 아시아태평양 커버리지.', 'why'),

('why_india', 'en', 'India', 'why'),
('why_india', 'zh', '印度', 'why'),
('why_india', 'ja', 'インド', 'why'),
('why_india', 'ko', '인도', 'why'),
('why_india', 'vi', 'An Do', 'why'),
('why_india', 'th', 'อินเดีย', 'why'),
('why_india', 'ms', 'India', 'why'),

-- ── Trust Section ──
('why_trust_title', 'en', 'Data You Can Verify', 'why'),
('why_trust_title', 'zh', '您可以验证的数据', 'why'),
('why_trust_title', 'zh-TW', '您可以驗證的數據', 'why'),
('why_trust_title', 'vi', 'Du lieu ban co the xac minh', 'why'),
('why_trust_title', 'th', 'ข้อมูลที่คุณตรวจสอบได้', 'why'),
('why_trust_title', 'ms', 'Data Yang Boleh Anda Sahkan', 'why'),
('why_trust_title', 'ja', '検証可能なデータ', 'why'),
('why_trust_title', 'ko', '검증 가능한 데이터', 'why'),

('why_trust_sub', 'en', 'Our OHLCV data matches Google Finance. Don''t take our word for it — check it yourself.', 'why'),
('why_trust_sub', 'zh', '我们的OHLCV数据与Google Finance一致。不信？您可以自己验证。', 'why'),
('why_trust_sub', 'vi', 'Du lieu OHLCV cua chung toi khop voi Google Finance. Hay tu kiem tra.', 'why'),
('why_trust_sub', 'ja', '当社のOHLCVデータはGoogle Financeと一致します。ご自身でご確認ください。', 'why'),
('why_trust_sub', 'ko', '우리의 OHLCV 데이터는 Google Finance와 일치합니다. 직접 확인해 보세요.', 'why'),

('why_trust_time', 'en', 'Time', 'why'),
('why_trust_time', 'zh', '时间', 'why'),
('why_trust_time', 'ja', '時間', 'why'),
('why_trust_time', 'ko', '시간', 'why'),

('why_trust_statement', 'en', '"Our stock price data matches Google Finance — Open, High, Low, Close, Volume. Every market, every stock, every time."', 'why'),
('why_trust_statement', 'zh', '"我们的股票价格数据与Google Finance一致——开盘、最高、最低、收盘、成交量。每个市场，每只股票，每一次。"', 'why'),
('why_trust_statement', 'vi', '"Du lieu gia co phieu cua chung toi khop voi Google Finance — Mo cua, Cao nhat, Thap nhat, Dong cua, Khoi luong. Moi thi truong, moi co phieu, moi luc."', 'why'),
('why_trust_statement', 'ja', '「当社の株価データはGoogle Financeと一致します — 始値、高値、安値、終値、出来高。すべての市場、すべての銘柄、毎回。」', 'why'),
('why_trust_statement', 'ko', '"우리의 주가 데이터는 Google Finance와 일치합니다 — 시가, 고가, 저가, 종가, 거래량. 모든 시장, 모든 종목, 매번."', 'why'),

('why_trust_date', 'en', 'BHP Group Limited (ASX: BHP) — April 1, 2026', 'why'),
('why_trust_date', 'zh', 'BHP集团有限公司 (ASX: BHP) — 2026年4月1日', 'why'),

-- ── AI Features ──
('why_ai_title', 'en', 'A Research Platform, Not a Chatbot', 'why'),
('why_ai_title', 'zh', '研究平台，而非聊天机器人', 'why'),
('why_ai_title', 'zh-TW', '研究平台，而非聊天機器人', 'why'),
('why_ai_title', 'vi', 'Nen tang nghien cuu, khong phai chatbot', 'why'),
('why_ai_title', 'th', 'แพลตฟอร์มวิจัย ไม่ใช่แชทบอท', 'why'),
('why_ai_title', 'ms', 'Platform Penyelidikan, Bukan Chatbot', 'why'),
('why_ai_title', 'ja', 'チャットボットではなく、リサーチプラットフォーム', 'why'),
('why_ai_title', 'ko', '챗봇이 아닌 리서치 플랫폼', 'why'),

('why_ai_sub', 'en', 'Accurate data is just the foundation. DataP.ai combines real-time prices with proprietary AI analysis.', 'why'),
('why_ai_sub', 'zh', '准确的数据只是基础。DataP.ai将实时价格与专有AI分析相结合。', 'why'),
('why_ai_sub', 'vi', 'Du lieu chinh xac chi la nen tang. DataP.ai ket hop gia thoi gian thuc voi phan tich AI doc quyen.', 'why'),
('why_ai_sub', 'ja', '正確なデータは基盤に過ぎません。DataP.aiはリアルタイム価格と独自のAI分析を組み合わせます。', 'why'),
('why_ai_sub', 'ko', '정확한 데이터는 기반일 뿐입니다. DataP.ai는 실시간 가격과 독자적인 AI 분석을 결합합니다.', 'why'),

('why_feat1_title', 'en', 'Website Intelligence', 'why'),
('why_feat1_title', 'zh', '网站情报', 'why'),
('why_feat1_desc', 'en', 'Know when company IR pages change before the market reacts. Our agents monitor thousands of corporate pages 24/7.', 'why'),
('why_feat1_desc', 'zh', '在市场反应之前了解公司IR页面的变化。我们的代理24/7监控数千个企业页面。', 'why'),

('why_feat2_title', 'en', 'Multi-Agent Analysis', 'why'),
('why_feat2_title', 'zh', '多代理分析', 'why'),
('why_feat2_desc', 'en', 'Multiple AI agents analyse each stock independently, then debate and cross-validate. Only consensus signals survive.', 'why'),
('why_feat2_desc', 'zh', '多个AI代理独立分析每只股票，然后辩论和交叉验证。只有共识信号才能通过。', 'why'),

('why_feat3_title', 'en', 'Smart Alerts', 'why'),
('why_feat3_title', 'zh', '智能提醒', 'why'),
('why_feat3_desc', 'en', 'Price, volume, and IR-change alerts delivered in your language, in your timezone. Never miss a signal.', 'why'),
('why_feat3_desc', 'zh', '价格、成交量和IR变更提醒，以您的语言、您的时区发送。永不错过信号。', 'why'),

('why_feat4_title', 'en', 'Custom Strategies', 'why'),
('why_feat4_title', 'zh', '自定义策略', 'why'),
('why_feat4_desc', 'en', 'Build, backtest, and deploy your own AI strategy in our Studio. 5 years of historical data. Your strategy, your edge.', 'why'),
('why_feat4_desc', 'zh', '在我们的Studio中构建、回测和部署您自己的AI策略。5年历史数据。您的策略，您的优势。', 'why'),

-- ── CTA Section ──
('why_cta_title', 'en', 'Ready to See the Difference?', 'why'),
('why_cta_title', 'zh', '准备好看到差异了吗？', 'why'),
('why_cta_title', 'zh-TW', '準備好看到差異了嗎？', 'why'),
('why_cta_title', 'vi', 'San sang thay su khac biet?', 'why'),
('why_cta_title', 'th', 'พร้อมเห็นความแตกต่างแล้วหรือยัง?', 'why'),
('why_cta_title', 'ms', 'Sedia Melihat Perbezaannya?', 'why'),
('why_cta_title', 'ja', '違いを体験する準備はできましたか？', 'why'),
('why_cta_title', 'ko', '차이를 확인할 준비가 되셨나요?', 'why'),

('why_cta_sub', 'en', 'Join thousands of self-directed investors across 13 Asia-Pacific markets.', 'why'),
('why_cta_sub', 'zh', '加入13个亚太市场的数千名自主投资者。', 'why'),
('why_cta_sub', 'vi', 'Tham gia hang nghin nha dau tu tu chu tai 13 thi truong Chau A-Thai Binh Duong.', 'why'),
('why_cta_sub', 'ja', 'アジア太平洋13市場の何千人もの個人投資家に参加しましょう。', 'why'),
('why_cta_sub', 'ko', '아시아태평양 13개 시장의 수천 명의 자기주도 투자자와 함께하세요.', 'why'),

('why_cta_start', 'en', 'Start Free', 'why'),
('why_cta_start', 'zh', '免费开始', 'why'),
('why_cta_start', 'vi', 'Bat dau mien phi', 'why'),
('why_cta_start', 'ja', '無料で始める', 'why'),
('why_cta_start', 'ko', '무료로 시작', 'why'),

('why_cta_partner', 'en', 'Partner With Us', 'why'),
('why_cta_partner', 'zh', '与我们合作', 'why'),
('why_cta_partner', 'vi', 'Hop tac voi chung toi', 'why'),
('why_cta_partner', 'ja', 'パートナーシップ', 'why'),
('why_cta_partner', 'ko', '파트너십 문의', 'why'),

('why_cta_founders', 'en', 'Talk to Founders', 'why'),
('why_cta_founders', 'zh', '联系创始人', 'why'),
('why_cta_founders', 'vi', 'Noi chuyen voi nha sang lap', 'why'),
('why_cta_founders', 'ja', '創業者に相談', 'why'),
('why_cta_founders', 'ko', '창업자와 대화', 'why'),

('why_cta_trust', 'en', 'Trusted by self-directed investors across 13 Asia-Pacific markets', 'why'),
('why_cta_trust', 'zh', '受13个亚太市场自主投资者信赖', 'why'),
('why_cta_trust', 'vi', 'Duoc tin tuong boi cac nha dau tu tu chu tai 13 thi truong Chau A-Thai Binh Duong', 'why'),
('why_cta_trust', 'ja', 'アジア太平洋13市場の個人投資家に信頼されています', 'why'),
('why_cta_trust', 'ko', '아시아태평양 13개 시장의 자기주도 투자자들이 신뢰합니다', 'why')

ON CONFLICT (label_key, lang) DO UPDATE SET text = EXCLUDED.text, category = EXCLUDED.category;
